### PR TITLE
RHPAM-3661 - move all components to the groupId org.kie.kogito.examples

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by almope** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Review by evacchi — APPROVED** [review]

**Comment by mareknovotny** [comment]
we can for now ignore snyk run as it shows 3rd party dependency problems.

**Review by radtriste — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
GA are influenced by not enough memory? 
```
2021-05-17T07:33:24.4504101Z Going to parse results form **/*-reports/TEST-*.xml
2021-05-17T07:33:44.2792545Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:33:50.7108208Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:33:57.2784560Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:04.3955563Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:10.1084477Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:16.5015667Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:22.9522645Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:29.4402251Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:35.8634113Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:42.3066539Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:48.7325656Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:34:55.2513463Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:01.6826772Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:08.0697719Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:14.4541379Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:20.8602585Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:27.2594276Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:33.6414313Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:40.0836106Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
2021-05-17T07:35:46.5180823Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
```

**Comment by danielezonca** [comment]
> GA are influenced by not enough memory?
> 
> ```
> 2021-05-17T07:33:24.4504101Z Going to parse results form **/*-reports/TEST-*.xml
> 2021-05-17T07:33:44.2792545Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:33:50.7108208Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:33:57.2784560Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:04.3955563Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:10.1084477Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:16.5015667Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:22.9522645Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/OrdersRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:29.4402251Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:35.8634113Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:42.3066539Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:48.7325656Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonProcessIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:34:55.2513463Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:01.6826772Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:08.0697719Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:14.4541379Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:20.8602585Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:27.2594276Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:33.6414313Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:40.0836106Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> 2021-05-17T07:35:46.5180823Z kiegroup_kogito_examples/kogito-examples/process-quarkus-example/src/test/java/org/kie/kogito/examples/PersonsRestIT.java:1 | java.lang.IllegalStateException: Failed to load ApplicationContext Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
> ```

Yes they are mainly influenced by disk space, I was getting this error only building `kogito-apps` but it seems that also `examples` repo is affected (the main aspect is docker, when we use docker every build it uses much more disk space).
[This PR #695](https://github.com/kiegroup/kogito-examples/pull/695) adds the cleanup step also to `examples` repo so that a similar error should not happen anymore

**Pull request merged**
