### PR TITLE
[stable] Bump Quarkus 2.2.2.Final

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by antncl** [comment]
@radtriste should we not bump to 2.2.3? it will be the build we target in product (unless there is another build)

**Comment by radtriste** [comment]
`stable` is the release version. For now I am trying to have a consistent env ;)

**Comment by mareknovotny** [comment]
> `stable` is the release version. For now I am trying to have a consistent env ;)

@radtriste I am not sure what consistent env is? ;) but if we don't have upgrade in kogito-runtimes and optaplanner we probably waste time on upgrading to 2.2.2.Final now and we should do directly to latest released version of Quarkus, which is now 2.2.3.Final. Or am I missing what gives us this additional upgrade to 2.2.2.Final? I mean we do not necessary need this.

**Comment by radtriste** [comment]
well 2.2.2.Final was updated on runtimes/optaplanner but not on examples as the script was not updated ... I am trying to fix that.
anyway `stable` is the already released version, so corresponding right now to `1.11.1` tag. as there is no further planned community release on 1.11.x for now, we should update the `stable` branch with correct version of Quarkus.

For the 2 other PRs on main and 1.11.x, we could indeed update to 2.2.3.Final directly.

**Comment by mareknovotny** [comment]
ok. thanks for explanation

**Review by mareknovotny — APPROVED** [review]
looks ok after explaining the reason.
jenkins retest this please

**Comment by mareknovotny** [comment]
Error seems strange
`Run kiegroup/github-action-build-chain@v2.6.2
Error:   Definition file https://raw.githubusercontent.com/${GROUP}/kogito-pipelines/${BRANCH}/.ci/pull-request-config.yaml does not exist for any of these cases: https://raw.githubusercontent.com/radtriste/kogito-pipelines/stable-bump-stable-quarkus-2.2.2.Final/.ci/pull-request-config.yaml, https://raw.githubusercontent.com/kiegroup/kogito-pipelines/stable-bump-stable-quarkus-2.2.2.Final/.ci/pull-request-config.yaml or https://raw.githubusercontent.com/kiegroup/kogito-pipelines/stable/.ci/pull-request-config.yaml`

**Comment by radtriste** [comment]
yeah there is no mapping for `stable` branch so it cannot find it ... will just run a nightly on that branch

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
job started https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-examples-stable/3/

**Comment by radtriste** [comment]
rebuild: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-examples-stable/4/

**Review by evacchi — APPROVED** [review]

**Comment by radtriste** [comment]
job is green. gonna merge that PR

**Pull request merged**
