### PR TITLE
KOGITO-3876  Bump to Quarkus 1.10.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
relates https://github.com/kiegroup/kogito-runtimes/pull/898

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@evacchi please also bump keycloak to 11.0.2

**Comment by evacchi** [comment]
@cristianonicolai done

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
