### PR TITLE
[KOGITO-3471] Extract kogito-examples nightly/release pipeline from runtimes

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-3471

With introduction from Optaplanner, we need to extract kogito-examples as examples depend on both runtimes and optaplanner.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Review by sutaakar — APPROVED** [review]

**Review by Kevin-Mok — APPROVED** [review]
So, will another PR will be created for the release pipeline to add these jobs as part of it?

Also, I believe that we have many shared helper functions across multiple Jenkinsfile's in different repositories that probably should be refactored into the shared library at some point?

**Comment by radtriste** [comment]
yes that one: https://github.com/kiegroup/kogito-pipelines/pull/67

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
