### PR TITLE
Fix #1866 - Remove Kogito Operator CRs and citations

### LINKED ISSUE #1866: Remove references from the Kogito Operator
See https://github.com/apache/incubator-kie-kogito-operator/issues/1537

### PR DESCRIPTION
**Pull request by ricardozanini**
See https://github.com/apache/incubator-kie-kogito-operator/issues/1537

I've removed the Trusty Demonstration example since it relies on the Kogito Operator and pretty old binaries and libraries. To maintain it in the repo, it would have to upgrade/review the whole demo. 

The SonataFlow Github Showcase was not removed because we deprecated and there's the intention to bring it back, I just need to prioritize.

Every citation and operator's CRs were removed for good.

### CODE REVIEW

**Comment by ricardozanini** [comment]
@lucamolteni @gitgabrio not sure who's responsible for Trusty now? Just to let you know I've removed the Trusty Demo from the repo.

**Comment by gitgabrio** [comment]
@ricardozanini IINW, I'm the only one left of the "trusty" initiative, but I dealt almost only on the PMML implementation.
About Trusty (and Trusty Demo) I think there was interesting stuff in it, that we may want to retrieve when we have some time. With that in mind, I think it would be better to "disable" the Trusty Demo project (i.e. remove from reactor) instead of completely remove it. If we delete it now, it would be hard in future to remember it was there and how it was done, unless we start looking backard in commits ? WDYT ? <- @porcelli

**Comment by lucamolteni** [comment]
> @lucamolteni @gitgabrio not sure who's responsible for Trusty now? Just to let you know I've removed the Trusty Demo from the repo.

@ruivieira @RobGeada ?

**Review by domhanak — APPROVED** [review]
Ok from serverless side.

**Comment by ricardozanini** [comment]
@gitgabrio I can revert it, but honestly, it can bring more harm than good since it's super old and won't work at all. It dates back to Kogito 1.7.

**Comment by gitgabrio** [comment]
> @gitgabrio I can revert it, but honestly, it can bring more harm than good since it's super old and won't work at all. It dates back to Kogito 1.7.

@ricardozanini I see your point, ok

**Review by porcelli — APPROVED** [review]
lgtm! thank you

**Review by wmedvede — APPROVED** [review]

**Review by pefernan — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Pull request merged**
