### PR TITLE
KOGITO-5712 Include process related examples to productized profile

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Jenkins rerun examples tests

**Review by tiagodolphine — APPROVED** [review]

**Review by mareknovotny — APPROVED** [review]
thanks @cristianonicolai

**Review by fjtirado — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Pull request merged**
