### PR TITLE
KOGITO-3698: Avoid to use com.google.common.io package

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3698
Description: Using this package is making the pipeline failed. Therefore, we should use the apache utils instead.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by ricardozanini** [comment]
Thanks @Sgitario ! Have you run the example locally with this changes calling the actual GitHub API?

**Comment by Sgitario** [comment]
I did check that the example is now building correctly using the latest version of quarkus and 1.9 version. Also, the tests are passing.

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
I'd say to run this example with actual credentials: https://github.com/kiegroup/kogito-examples/blob/master/serverless-workflow-github-showcase/github-service/src/test/java/org/kogito/examples/sw/github/service/GitHubWrapperServiceIT.java

Or at least write an unit test to verify this function alone.

**Comment by Sgitario** [comment]
@ricardozanini I verified the changes manually (I've installed a github app on one repository within my github user following the README instructions).

**Comment by ricardozanini** [comment]
@Sgitario let's wait for it to be green then and merge, #386 depends on it.

**Comment by evacchi** [comment]
also https://github.com/kiegroup/kogito-runtimes/pull/826

**Review by sutaakar — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Pull request merged**
