### PR TITLE
KOGITO-6131 Enable codegen when RESTEasy reactive is used

### PR DESCRIPTION
**Pull request by tkobayas**
- use @QuarkusIntegrationTest instead of @QuarkusTest to handle static resources generated by codegen

https://issues.redhat.com/browse/KOGITO-6131

https://github.com/kiegroup/kogito-runtimes/pull/1757

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
This error is found in daily build so not related to this PR.
```
[2021-12-01T07:33:10.084Z] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 6.919 s <<< FAILURE! - in org.acme.sw.onboarding.queries.AssignmentUnitTest
[2021-12-01T07:33:10.084Z] [ERROR] org.acme.sw.onboarding.queries.AssignmentUnitTest.verifyNeurologyAssignmentCollection  Time elapsed: 0 s  <<< ERROR!
[2021-12-01T07:33:10.084Z] java.lang.RuntimeException:
[2021-12-01T07:33:10.084Z] java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[2021-12-01T07:33:10.084Z]      [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value quarkus.http.test-port in property org.acme.sw.onboarding.services.AssignmentUnitClient/mp-rest/url
[2021-12-01T07:33:10.084Z]      at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:63)
```

**Review by danielezonca — APPROVED** [review]

**Comment by tkobayas** [comment]
(build) kogito-examples : flaky tests. Not related to this PR.
```
[2021-12-16T09:57:41.385Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 53.795 s <<< FAILURE! - in org.acme.travel.tests.messaging.quarkus.MessagingIT
[2021-12-16T09:57:41.385Z] [ERROR] org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess  Time elapsed: 12.024 s  <<< FAILURE!
[2021-12-16T09:57:41.385Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
[2021-12-16T09:57:41.385Z]      at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)


[2021-12-16T09:58:53.600Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 52.649 s <<< FAILURE! - in org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT
[2021-12-16T09:58:53.600Z] [ERROR] org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess  Time elapsed: 11.938 s  <<< FAILURE!
[2021-12-16T09:58:53.600Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
[2021-12-16T09:58:53.600Z]      at org.acme.travel.tests.multimessaging.quarkus.MultiMessagingIT.testProcess(MultiMessagingIT.java:105)


[2021-12-16T10:00:00.467Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 47.11 s <<< FAILURE! - in org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT
[2021-12-16T10:00:00.467Z] [ERROR] org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess  Time elapsed: 13.12 s  <<< FAILURE!
[2021-12-16T10:00:00.467Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
[2021-12-16T10:00:00.467Z]      at org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess(MultiMessagingIT.java:96)


[2021-12-16T10:00:58.206Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 46.519 s <<< FAILURE! - in org.acme.travel.tests.messaging.springboot.MessagingIT
[2021-12-16T10:00:58.206Z] [ERROR] org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess  Time elapsed: 13.568 s  <<< FAILURE!
[2021-12-16T10:00:58.206Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
[2021-12-16T10:00:58.206Z]      at org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess(MessagingIT.java:94)
```

**Comment by tkobayas** [comment]
Jenkins run native

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins run native

**Comment by tkobayas** [comment]
(native) kogito-examples:
```
[2021-12-17T14:31:14.942Z] [serverless-workflow-callback-quarkus-runner:26]     analysis: 148,978.05 ms,  5.58 GB
[2021-12-17T14:31:14.942Z] Error: Classes that should be initialized at run time got initialized during image building:
[2021-12-17T14:31:14.942Z]  java.sql.DriverManager the class was requested to be initialized at run time (from jar:file:///project/lib/com.oracle.database.jdbc.ojdbc11-21.3.0.0.jar!/META-INF/native-image/native-image.properties with 'java.sql.DriverManager'). To see why java.sql.DriverManager got initialized use --trace-class-initialization=java.sql.DriverManager
[2021-12-17T14:31:14.942Z]
[2021-12-17T14:31:14.942Z] com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
[2021-12-17T14:31:14.942Z]  java.sql.DriverManager the class was requested to be initialized at run time (from jar:file:///project/lib/com.oracle.database.jdbc.ojdbc11-21.3.0.0.jar!/META-INF/native-image/native-image.properties with 'java.sql.DriverManager'). To see why java.sql.DriverManager got initialized use --trace-class-initialization=java.sql.DriverManager
[2021-12-17T14:31:14.942Z]
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
[2021-12-17T14:31:14.942Z]      at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[2021-12-17T14:31:14.942Z] [serverless-workflow-callback-quarkus-runner:26]      [total]: 193,738.79 ms,  5.58 GB
[2021-12-17T14:31:14.942Z] # Printing build artifacts to: /project/serverless-workflow-callback-quarkus-runner.build_artifacts.txt
[2021-12-17T14:31:14.942Z] Error: Image build request failed with exit status 1
```

The same error is found in daily builds. So not likely related to this PR.

https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fnightly%2Fkogito-examples-native/detail/kogito-examples-native/85/pipeline/191

**Comment by tkobayas** [comment]
Jenkins run native

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
(build) kogito-examples  : flaky test
```
[2021-12-24T06:27:19.676Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.729 s <<< FAILURE! - in org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT
[2021-12-24T06:27:19.676Z] [ERROR] org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess  Time elapsed: 12.562 s  <<< FAILURE!
[2021-12-24T06:27:19.676Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
```

**Pull request merged**
