### PR TITLE
[KOGITO-5444] Update Examples to use the new SB starter

### PR DESCRIPTION
**Pull request by ricardozanini**
Small update to use the new Spring Boot Starter. 

Related PR:

- https://github.com/kiegroup/kogito-runtimes/pull/1443

### CODE REVIEW

**Review by danielezonca — COMMENTED** [review]
Why aren't we use the new specific starters?

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by ricardozanini** [comment]
Blocked by:

- https://github.com/kiegroup/kogito-runtimes/pull/1497

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by ricardozanini** [comment]
@cristianonicolai we need to merge https://github.com/kiegroup/kogito-runtimes/pull/1497 first before running the tests. It will fail.

**Comment by ricardozanini** [comment]
jenkins retest this

**Pull request merged**
