### PR TITLE
[KOGITO-6360] Updating examples

### PR DESCRIPTION
**Pull request by fjtirado**
Depends on https://github.com/kiegroup/kogito-runtimes/pull/1776

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins rerun kogito-examples tests

**Review by cristianonicolai — APPROVED** [review]

**Comment by fjtirado** [comment]
jenkins rerun kogito-examples tests

**Comment by fjtirado** [comment]
jenkins rerun kogito-examples tests

**Comment by cristianonicolai** [comment]
@ricardozanini looks good to you?

**Pull request merged**
