### PR TITLE
[KOGITO-6999] Publishing variable events

### PR DESCRIPTION
**Pull request by fjtirado**
Depends on https://github.com/kiegroup/kogito-runtimes/pull/2158

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#634` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 452
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/634/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.springboot.outbox.OutboxIT 1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <2><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events, kogito-variables-events]><br/> within 1 minutes.<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents(OutboxIT.java:187)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <2><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events, kogito-variables-events]><br/><br/>	at org.kie.kogito.springboot.outbox.OutboxIT.lambda$testSendProcessEvents$4(OutboxIT.java:194)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/634/display/redirect

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#636` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 452
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/636/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.springboot.outbox.OutboxIT 1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <2><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events, kogito-variables-events]><br/> within 1 minutes.<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents(OutboxIT.java:187)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <2><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events, kogito-variables-events]><br/><br/>	at org.kie.kogito.springboot.outbox.OutboxIT.lambda$testSendProcessEvents$4(OutboxIT.java:194)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/636/display/redirect

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
