### PR TITLE
KOGITO-5664 - Review Kafka client usage

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1543
- https://github.com/kiegroup/kogito-examples/pull/866

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by ricardozanini — APPROVED** [review]
Now we have specific testing for each runtime? :)

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by r00ta — APPROVED** [review]

**Pull request merged**
