### PR TITLE
Update to Stunner!

### PR DESCRIPTION
**Pull request by porcelli**
Update the XML format to Stunner, so it can look good in VSCode

### CODE REVIEW

**Comment by evacchi** [comment]
is this PR outdated?

**Comment by porcelli** [comment]
i think so, i think @inodeman has been working on updating stuff around... right?

**Comment by porcelli** [comment]
ops.. I think this might be still valid :o

we need convert the current file to stunner.

**Comment by domhanak** [comment]
Closing as outdated

**Pull request closed without merging**
