### PR TITLE
KOGITO-3659 - Remove duplicate services for SW GH example

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Removing duplicate code is always good. Depends on: https://github.com/kiegroup/kogito-runtimes/pull/925

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by ricardozanini** [comment]
Jenkins retest this please

**Comment by ricardozanini** [comment]
Failing on jobs service:

```
Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (verify) on project jobs-service: There are test failures.


2020-12-09 11:05:58,015 INFO  [org.kie.kog.job.ser.mod.job.HttpJob] (vert.x-eventloop-thread-11) Executing for context JobDetails[id='fc804bd0-2205-4501-9bf9-dcf5d300270c', correlationId='fc804bd0-2205-4501-9bf9-dcf5d300270c', status=null, lastUpdate=2020-12-09T16:05:58.011Z[UTC], retries=0, executionCounter=0, scheduledId='null', payload=null, recipient=HTTPRecipient[endpoint='http://localhost:8081/callback'], trigger=PointInTimeTrigger @ Wed Dec 09 10:55:58 EST 2020, type=HTTP]
2020-12-09 11:05:58,023 INFO  [org.kie.kog.job.ser.exe.HttpJobExecutor] (vert.x-eventloop-thread-0) handle success JobExecutionResponse[message='OK', code='200', timestamp=2020-12-09T11:05:58.022900-05:00[America/New_York], jobId='fc804bd0-2205-4501-9bf9-dcf5d300270c']
2020-12-09 11:05:58,066 ERROR [org.kie.kog.job.ser.res.err.DefaultErrorMapper] (vert.x-worker-thread-19) Handling HTTP Error: java.lang.IllegalArgumentException: SRMSG00023: `null` is not a valid value
	at io.smallrye.reactive.messaging.extension.EmitterImpl.send(EmitterImpl.java:26)
	at org.kie.kogito.jobs.service.stream.JobStreams.publishJobStatusChange(JobStreams.java:76)
	at org.kie.kogito.jobs.service.stream.JobStreams_ClientProxy.publishJobStatusChange(JobStreams_ClientProxy.zig:207)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.kie.kogito.jobs.service.repository.impl.BaseReactiveJobRepository.lambda$runAsync$0(BaseReactiveJobRepository.java:47)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.508 s <<< FAILURE! - in org.kie.kogito.jobs.service.resource.JobResourceIT
[ERROR] testForcingCreateExpiredJob  Time elapsed: 0.103 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

	at org.kie.kogito.jobs.service.resource.JobResourceIT.testForcingCreateExpiredJob(JobResourceIT.java:283)
```

@tiagodolphine do you know more about it? Can you shed a light here?

**Comment by ricardozanini** [comment]
Jenkins retest this please

**Comment by tiagodolphine** [comment]
jenkins retest this

**Pull request merged**
