### PR TITLE
incubator-kie-issues/issues#697 Disable flaky tests in incubator-kie-kogito-examples

### PR DESCRIPTION
**Pull request by Rikkola**
Closes https://github.com/apache/incubator-kie-kogito-examples/issues/1831

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Bad license merge. Fixing.

**Comment by domhanak** [comment]
@Rikkola is there an issue that will cover fixing them? if so please tag me there, thanks

**Comment by Rikkola** [comment]
@domhanak I think that is something that we need, but I am not sure where to add these. I assume there will be several tests like these and each one would need a ticket. Should I make one for each into incubator-kie-issues? 

Problem is, I doubt there will be a rush to fix these. So they will stay there open for a while. Then many people look at the tickets to see how healthy the project is, and in this case the issues will make that list bigger. If there are no plans to fix, then maybe it would be better to delete these?

**Comment by ricardozanini** [comment]
@domhanak @jstastny-cz @Rikkola please open issues in this repo and a fup mail to the devlist, so the community is aware.

**Comment by Rikkola** [comment]
@ricardozanini ok a ticket for this repo makes sense

**Comment by domhanak** [comment]
@Rikkola @ricardozanini :+1: the issue would be something like `Reevaluate these tests` with the goal to fix the flaky-ness or cover the hole we have in coverage because of its removal.

**Comment by ricardozanini** [comment]
> @Rikkola @ricardozanini 👍 the issue would be something like `Reevaluate these tests` with the goal to fix the flaky-ness or cover the hole we have in coverage because of its removal.

Makes sense to me.

**Review by domhanak — COMMENTED** [review]
Link the issue here and we can merge. @Rikkola

**Comment by jstastny-cz** [comment]
Issue is tracked against the target repo: apache/incubator-kie-kogito-examples#1831

Though one thing - I think ignoring the test does not put them into the results as skipped, as is done for other tests currently being disabled - e.g. those OutboxIT in https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fpullrequest_jobs%2Fkogito-examples-pr/detail/PR-1830/6/tests

**Comment by Rikkola** [comment]
@jstastny-cz true it does not. And that explains why the other tests were not just Ignored. I will update the PR with that approach.

**Review by ricardozanini — APPROVED** [review]

**Comment by Rikkola** [comment]
@jstastny-cz @domhanak Is this fine to be merged?

**Comment by jstastny-cz** [comment]
I thought you wanted to have the test shown as skipped in test results, based on previous discussion.

**Comment by Rikkola** [comment]
I do want to, but I likely did not get that result with what I did. Let me recheck.

**Comment by Rikkola** [comment]
Right should use disabled, I still went with ignored.

**Review by domhanak — APPROVED** [review]

**Comment by Rikkola** [comment]
@jstastny-cz Is there a way to make sure the build skipped the tests, not ignored them?

**Comment by kie-ci3** [comment]
**PR job** `#10` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1830 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/display/redirect

**Test results:**
- PASSED: 336
- FAILED: 35

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.flexible.example.quarkus/ServiceDeskProcessTest/testSupportCaseExample/">org.kie.kogito.flexible.example.quarkus.ServiceDeskProcessTest.testSupportCaseExample</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.deals/DealsRestIT/PR_check___Build_projects___testDealsRest/">PR check / Build projects / org.acme.deals.DealsRestIT.testDealsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.deals/DealsRestIT/PR_check___Build_projects___testDealsRest/">PR check / Build projects / org.acme.deals.DealsRestIT.testDealsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.deals/DealsRestIT/PR_check___Build_projects___testDealsRest/">PR check / Build projects / org.acme.deals.DealsRestIT.testDealsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.deals/DealsRestIT/PR_check___Build_projects___testDealsRest/">PR check / Build projects / org.acme.deals.DealsRestIT.testDealsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.deals/DealsRestIT/PR_check___Build_projects___testDealsRest/">PR check / Build projects / org.acme.deals.DealsRestIT.testDealsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/OrdersRestIT/testOrdersWithOrderItemsAbortedRest/">org.kie.kogito.examples.OrdersRestIT.testOrdersWithOrderItemsAbortedRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/OrdersRestIT/testOrdersWithOrderItemsRest/">org.kie.kogito.examples.OrdersRestIT.testOrdersWithOrderItemsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestWithSecurityPolicyAndLifeCycles/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestWithSecurityPolicyAndLifeCycles</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestRetriggerNodeViaMgmtInterface/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestRetriggerNodeViaMgmtInterface</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testPersonsRestStartFromUserTask/">org.kie.kogito.examples.PersonsRestIT.testPersonsRestStartFromUserTask</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRest/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestCancelAndTriggerNodeViaMgmtInterface/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestCancelAndTriggerNodeViaMgmtInterface</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestWithSecurityPolicyNotAuthorized/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestWithSecurityPolicyNotAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <0><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestAbortViaMgmtInterface/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestAbortViaMgmtInterface</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestWithSecurityPolicy/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestWithSecurityPolicy</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.travels/ApprovalsRestIT/PR_check___Build_projects___testStartApprovalAuthorized/">PR check / Build projects / org.acme.travels.ApprovalsRestIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.travels/ApprovalsRestIT/PR_check___Build_projects___testStartApprovalAuthorized/">PR check / Build projects / org.acme.travels.ApprovalsRestIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.travels/ApprovalsRestIT/PR_check___Build_projects___testStartApprovalAuthorized/">PR check / Build projects / org.acme.travels.ApprovalsRestIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.travels/ApprovalsRestIT/PR_check___Build_projects___testStartApprovalAuthorized/">PR check / Build projects / org.acme.travels.ApprovalsRestIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.travels.security.quarkus/ApprovalsRestTest/testStartApprovalAuthorized/">org.acme.travels.security.quarkus.ApprovalsRestTest.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.flexible.example.springboot/ServiceDeskProcessTest/testSupportCaseExample/">org.kie.kogito.flexible.example.springboot.ServiceDeskProcessTest.testSupportCaseExample</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/OrdersRestIT/testOrdersWithOrderItemsAbortedRest/">org.kie.kogito.examples.demo.OrdersRestIT.testOrdersWithOrderItemsAbortedRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/OrdersRestIT/testOrdersWithOrderItemsRest/">org.kie.kogito.examples.demo.OrdersRestIT.testOrdersWithOrderItemsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestWithSecurityPolicyAndLifeCycles/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestWithSecurityPolicyAndLifeCycles</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestRetriggerNodeViaMgmtInterface/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestRetriggerNodeViaMgmtInterface</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testPersonsRestStartFromUserTask/">org.kie.kogito.examples.demo.PersonsRestIT.testPersonsRestStartFromUserTask</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRest/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRest</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestCancelAndTriggerNodeViaMgmtInterface/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestCancelAndTriggerNodeViaMgmtInterface</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestWithSecurityPolicyNotAuthorized/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestWithSecurityPolicyNotAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <0><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestAbortViaMgmtInterface/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestAbortViaMgmtInterface</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestWithSecurityPolicy/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestWithSecurityPolicy</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme.travels.security.springboot/ApprovalsRestTest/testStartApprovalAuthorized/">org.acme.travels.security.springboot.ApprovalsRestTest.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>JSON path $.size doesn't match.<br/>Expected: is <1><br/>  Actual: <[]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:247)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:833)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:372)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:397)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)<br/> ... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 17 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:953)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)<br/> ... 19 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1830/10/testReport/org.acme/AcmeExchangeResourceIT/unauthorizedTest/">org.acme.AcmeExchangeResourceIT.unauthorizedTest</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:247)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:833)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:372)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:397)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)<br/> ... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 17 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:953)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)<br/> ... 19 more<br/>
</details>

**Pull request merged**
