### PR TITLE
quarkus 2.16.12.Final bump

### PR DESCRIPTION
**Pull request by porcelli**
quarks bump to 2.16.12.Final

### CODE REVIEW

**Comment by porcelli** [comment]
@mariofusco I sense you left this behind in the quarkus upgrade PRs

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1818 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1818/1/display/redirect

**Test results:**
- PASSED: 378
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1818/1/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [8083, 39383] should be listening)
</details>

**Review by mariofusco — APPROVED** [review]

**Review by baldimir — APPROVED** [review]

**Comment by porcelli** [comment]
what are the thoughts about the failing test? I can't see how it relates.. looks like an env problem (Timed out).

@jstastny-cz any input?

**Comment by jstastny-cz** [comment]
OutboxIT is often unstable.

**Comment by baldimir** [comment]
If it is unstable, I would say let's fix it or delete it. Of course in a separate PR.

**Comment by jstastny-cz** [comment]
> If it is unstable, I would say let's fix it or delete it. Of course in a separate PR.

@baldimir Go ahead. That's what I asked for in the dev mailing list. I am not able to fix it myself and I don't have insight into how useful this example actually is.

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1818 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1818/2/display/redirect

**Test results:**
- PASSED: 374
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1818/2/testReport/org.kie.kogito.examples.quarkus/DashboardsListIT/testDashboardsListIsAvailable/">org.kie.kogito.examples.quarkus.DashboardsListIT.testDashboardsListIsAvailable</a></summary>
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1818/2/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [8083, 42037] should be listening)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1818/2/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [8080, 42084] should be listening)
</details>

**Comment by porcelli** [comment]
failing tests are unrelated and has been identified as flaky before as mentioned by @jstastny-cz - I'll move forward and merge

**Pull request merged**
