### PR TITLE
KOGITO-2207 Update examples with new read mode API

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly: 
- https://github.com/kiegroup/kogito-examples/pull/309
- https://github.com/kiegroup/kogito-runtimes/pull/652
- https://github.com/kiegroup/kie-docs/pull/2746

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@MarianMacik @tiagodolphine good to merge this as well?

**Review by tiagodolphine — APPROVED** [review]
LGTM, just one question, isn't the default mode MUTABLE, I mean, is it really necessary to explicitly use the parameter `.values(ProcessInstanceReadMode.MUTABLE)`?

**Comment by cristianonicolai** [comment]
`MUTABLE` is the default for `findById`. `READONLY` is the default for `values`.

**Pull request merged**
