### PR TITLE
KOGITO-1929 - Create advanced example for kogito + serverless workflo…

### PR DESCRIPTION
**Pull request by tsurdilo**
…w - spring boot

### CODE REVIEW

**Comment by tsurdilo** [comment]
serverless workflow services example for spring boot

**Review by cristianonicolai — APPROVED** [review]

**Review by ricardozanini — COMMENTED** [review]
@tsurdilo could you please also add an operator example. Same thing as this one:
https://github.com/kiegroup/kogito-examples/tree/master/serverless-workflow-greeting-quarkus/operator
(now I see that we are also missing for the other two examples as well) :cry:

**Comment by tsurdilo** [comment]
@ricardozanini added. ok ill add this to the other examples as well.  thanks!

**Comment by tsurdilo** [comment]
@ricardozanini https://github.com/kiegroup/kogito-examples/pull/238

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
