### PR TITLE
KOGITO-3799 Update master to 2.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly: 
- https://github.com/kiegroup/kogito-examples/pull/442
- https://github.com/kiegroup/kogito-runtimes/pull/877
- https://github.com/kiegroup/kogito-apps/pull/532

### CODE REVIEW

**Comment by rsynek** [comment]
@cristianonicolai shouldn't we use a snapshot of the version that is going to be released as the next one? That's the 1.1.0.Final, right? It could be updated by the release pipeline.

If we increase to the next major version, does it mean, according to https://semver.org/, that we are preparing for incompatible changes to start landing on the master branch?

**Comment by cristianonicolai** [comment]
@rsynek the idea, as it was with 1.0.0-SNAPSHOT is that we bump master only on major releases. Master will remain 2.0.0-SNAPSHOT while 2.0 goes out. That is so we avoid having to bump master for every single release. A similar approach is done by Quarkus using another version convention.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by ge0ffrey** [comment]
For OptaPlanner, we 'll set master to 8.1.0-SNAPSHOT

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by evacchi — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
