### PR TITLE
[KOGITO-5302] Disable fail on empty beans

### PR DESCRIPTION
**Pull request by fjtirado**
Just a quick fix for the example to work on native mode. 
We should consider to have a global customizer class where we set up that to false to all projects, but I let @danielezonca to think about this ;)

### CODE REVIEW

**Review by tiagodolphine — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
we do have a global objectmapper so if we do plan to allow this, then it is doable @danielezonca what were your concerns?

**Review by radtriste — APPROVED** [review]

**Comment by danielezonca** [comment]
> we do have a global objectmapper so if we do plan to allow this, then it is doable @danielezonca what were your concerns?

My main/only concern is that as far as I know, in native mode if a class has not been marked for reflection the marshalling will just skip that field during deserialisation and you get a `null`.
We already had in the past similar problem
https://github.com/kiegroup/kogito-runtimes/pull/1111
And the solution was to add the classes to serialisation (+ add some native test that verified the expected result in detail).

I'm not a Jackson expert (and even less with Jackson in native mode) but are we sure this `SerializationFeature.FAIL_ON_EMPTY_BEANS` property is a general solution for this problem? Does it cover scenarios where only part of the payload cannot be deserialised (like a field)?
If so I'm fine to move this fix to runtimes to be applied globally 👍

**Comment by fjtirado** [comment]
@danielezonca 
Generated classes are being included automatically by Quarkus. Thats why other example with no empty beans are workings fine. As I already mentioned in Zulip, explicityly adding the empty bean to reflection does not fix anything, because this class is already there. So, we do NOT need to change KogitoAssetProcessor to add anything there
@evacchi 
Where is this global object mapper defined?

**Comment by fjtirado** [comment]
I closed this one and opened https://github.com/kiegroup/kogito-runtimes/pull/1366 to disable fail on empty beans globally

**Pull request closed without merging**
