### PR TITLE
[KOGITO-6831] Add traces

### PR DESCRIPTION
**Pull request by fjtirado**
Adding more traces to find out whats happening when the kafka test fails. 
I will execute as many times as needed till the problem occur (I can bet now it will be green the first time ;))
In local environment it always work

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@fjtirado I'm hoping that https://github.com/kiegroup/kogito-examples/pull/1141 has resolved these random issues

**Comment by fjtirado** [comment]
> @fjtirado I'm hoping that #1141 has resolved these random issues

@cristianonicolai it was green, lets try again
jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#530` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/530/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/530/testReport/org.acme.travel.tests.messaging.springboot/MessagingIT/testProcess/">org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess(MessagingIT.java:94)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/530/display/redirect

**Comment by fjtirado** [comment]
hmmm, now we have the issue in the messaging (not multi) ones, let me try something in the properties

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#536` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/536/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `kogito_outgoing_stream`<br/>Caused by: java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `kogito_outgoing_stream`<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/536/testReport/org.kie.kogito.examples.demo/OutboxIT/___/">org.kie.kogito.examples.demo.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49237] should be listening)<br/>	at org.kie.kogito.examples.demo.OutboxIT.before(OutboxIT.java:81)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49237] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/536/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#538` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/538/testReport/org.acme.travel.tests.multimessaging.springboot/MultiMessagingIT/testProcess/">org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess(MultiMessagingIT.java:96)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/538/testReport/org.acme.travel.tests.messaging.springboot/MessagingIT/testProcess/">org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess(MessagingIT.java:94)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/538/display/redirect

**Review by cristianonicolai — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#548` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 453
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/548/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.quarkus.outbox.OutboxIT 1 expectation failed.<br/>Expected status code <200> but was <404>.<br/> within 1 minutes.<br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents(OutboxIT.java:129)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.lambda$testSendProcessEvents$1(OutboxIT.java:136)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/548/display/redirect

**Comment by fjtirado** [comment]
jenkins retest this

**Pull request merged**
