### PR TITLE
[1.13.x] Fixes for random test failures in SW events example

### PR DESCRIPTION
**Pull request by cristianonicolai**
Backport of changes from main branch.

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#38` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/38/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.quarkus.outbox.OutboxIT 1 expectation failed.<br/>Expected status code <200> but was <404>.<br/> within 1 minutes.<br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents(OutboxIT.java:131)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.lambda$testSendProcessEvents$1(OutboxIT.java:138)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/38/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49229] should be listening)<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:85)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49229] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/38/display/redirect

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#41` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 433
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/41/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.springboot.outbox.OutboxIT 1 expectation failed.<br/>Expected status code <200> but was <404>.<br/> within 1 minutes.<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents(OutboxIT.java:131)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.springboot.outbox.OutboxIT.lambda$testSendProcessEvents$1(OutboxIT.java:138)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/41/display/redirect

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
