### PR TITLE
[0.9.x] KOGITO-1607: unify bpmn2 vs bpmn file extension

### PR DESCRIPTION
**Pull request by jomarko**
Corollary of #167

### CODE REVIEW

**Review by radtriste — CHANGES_REQUESTED** [review]
files are deleted ... is that on purpose ?
shouldn't they be migrated to bpmn2 ?

**Comment by jomarko** [comment]
Yes it is on purpose. I guess during some conflict resolving we created copies of files by mistake. If you check process-quarkus-example and process-springboot-example after my change, they should contain just bpmn2 processes

I opened 4 PRs for 0.9.x, all are just cherry-picks, but this is "fix"

**Review by radtriste — APPROVED** [review]

**Comment by ricardozanini** [comment]
@jomarko just checking, but during my renaming process, I saw much more `bpmn` files in the repo. Do we only have these?

**Comment by jomarko** [comment]
@ricardozanini yes we still have as **bpmn** so **bpmn2** files in **kogito-examples**. My point was at least to do not mix in particular projects. In other words projects of **kogito-examples** now use either **bpmn2** or **bpmn**.

I would be for unification across whole **kogito-examples** however would need to be discussed with DOC team as it would affect them.

Even this PR was created as corollary as DOC review.

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
