### PR TITLE
[incubator-kie-issues-1439] UserTask Decouple codegen and interface from engine

### PR DESCRIPTION
**Pull request by elguardian**
depends on:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3655
https://github.com/apache/incubator-kie-drools/pull/6052

Closes: https://github.com/apache/incubator-kie-issues/issues/1439

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2009 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/display/redirect

**Test results:**
- PASSED: 358
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestWithSecurityPolicyAndLifeCycles/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestWithSecurityPolicyAndLifeCycles</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <400>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/testReport/org.kie.kogito.examples/PersonsRestIT/testChildPersonsRestWithSecurityPolicyNotAuthorized/">org.kie.kogito.examples.PersonsRestIT.testChildPersonsRestWithSecurityPolicyNotAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <403> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/testReport/org.kie.kogito.examples/ProcessSagaIT/testOrderSuccess/">org.kie.kogito.examples.ProcessSagaIT.testOrderSuccess</a></summary>
<br/>expected: "03e6cf79-3301-434b-b5e1-d6899b5639aa"<br/> but was: "_8EE09D40-0D96-4EC0-86E4-A3FB11B78EB0"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/testReport/org.kie.kogito.examples/ProcessSagaIT/testOrderFailure/">org.kie.kogito.examples.ProcessSagaIT.testOrderFailure</a></summary>
<br/>expected: "03e6cf79-3301-434b-b5e1-d6899b5639aa"<br/> but was: "_A4898FE5-A2BC-4D3C-90F2-7992CD7FB20C"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestWithSecurityPolicyAndLifeCycles/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestWithSecurityPolicyAndLifeCycles</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <400>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/1/testReport/org.kie.kogito.examples.demo/PersonsRestIT/testChildPersonsRestWithSecurityPolicyNotAuthorized/">org.kie.kogito.examples.demo.PersonsRestIT.testChildPersonsRestWithSecurityPolicyNotAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <403> but was <404>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2009 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/3/display/redirect

**Test results:**
- PASSED: 144
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/3/testReport/org.kie.kogito.examples.quarkus/GrafanaDockerComposeIT/testGrafanaDashboards/">org.kie.kogito.examples.quarkus.GrafanaDockerComposeIT.testGrafanaDashboards</a></summary>
1 expectation failed.<br/>JSON path title doesn't match.<br/>Expected: a collection containing "dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Operational Dashboard"<br/>  Actual: <[dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - Hello - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - hello - Operational Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Operational Dashboard]><br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2009 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/4/display/redirect

**Test results:**
- PASSED: 306
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/4/testReport/org.acme.travels.quarkus/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.quarkus.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <0> but was: <1>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2009/4/testReport/org.acme.travels.quarkus/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.quarkus.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <0> but was: <1>
</details>

**Review by pefernan — APPROVED** [review]
+1 when all is ready and green

**Review by gitgabrio — APPROVED** [review]

**Pull request merged**
