### PR TITLE
[KOGITO-1942] Updating examples

### PR DESCRIPTION
**Pull request by fjtirado**
Depends on https://github.com/kiegroup/kogito-runtimes/pull/719

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@fjtirado code looks good to me, can you also take a look in the README files, examples etc. I think some have requests/response examples that might have to be tweaked a little.

**Comment by fjtirado** [comment]
> @fjtirado code looks good to me, can you also take a look in the README files, examples etc. I think some have requests/response examples that might have to be tweaked a little.

Readme.md files updated (I hope I have updated all required ones)

**Comment by cristianonicolai** [comment]
@radtriste @sutaakar can you take a look as this might impact BDD tests?

**Review by cristianonicolai — APPROVED** [review]

**Comment by sutaakar** [comment]
Looks ok to me. The BDD tests will need to be updated once the PRs are merged.

**Pull request merged**
