### PR TITLE
Bump main Quarkus 2.6.0.Final

### PR DESCRIPTION
**Pull request by radtriste**
Please review and merge

- https://github.com/kiegroup/kogito-pipelines/pull/337
- https://github.com/kiegroup/kogito-runtimes/pull/1807
- https://github.com/kiegroup/optaplanner/pull/1736
- https://github.com/kiegroup/kogito-apps/pull/1169
- https://github.com/kiegroup/optaplanner-quickstarts/pull/254
- https://github.com/kiegroup/kogito-examples/pull/1047

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
related to the backport:

> [2021-12-17T16:09:40.546Z] Caused by: java.lang.IllegalArgumentException: Unsupported method parameter java.util.List<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> at java.util.List<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem>

weird because that seems to mean it's not really using Quarkus 2.6 ???

**Comment by manstis** [comment]
The extension won't run until the end application is constructed so this probably just highlights there's an extension without the needed change... or this PR didn't use a 2.6.0.Final friendly branch of `kogito-runtimes`?

**Comment by evacchi** [comment]
jenkins retest this

**Comment by radtriste** [comment]
> > ng.IllegalArgumentException: Unsupported method parameter java.util.List<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> at java.util.List<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem>

```
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:2.5.1.Final:build (default) on project serverless-workflow-expression-quarkus: Failed to build quarkus application
```
looks weird. maybe one example was not updated ... gonna check that

**Comment by radtriste** [comment]
@evacchi https://github.com/kiegroup/kogito-examples/pull/1047/commits/1b0f318c7d7b36dfcf65b51f353902edf646c277 ...

**Pull request merged**
