### PR TITLE
KOGITO-5525 Add native tests

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/803
- https://github.com/kiegroup/kogito-runtimes/pull/1460

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins run native

**Review by tiagodolphine — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins run native

**Pull request merged**
