### PR TITLE
[KOGITO-3155] Add DMN + PMML scesim to examples

### PR DESCRIPTION
**Pull request by danielezonca**
https://issues.redhat.com/browse/KOGITO-3155

This PR adds a `scesim` file to both DMN + PMML examples

PRs list:
- https://github.com/kiegroup/kogito-runtimes/pull/718
- https://github.com/kiegroup/kogito-examples/pull/344

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
@danielezonca 
lgtm

**Review by jomarko — COMMENTED** [review]
Looks fine,  however could we please add also scenario description? for example like attached:
Screenshot from 2020-08-25 10-28-42

**Comment by danielezonca** [comment]
@jomarko 
Done

**Review by yesamer — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
@danielezonca thank you for incorporating changes

**Pull request merged**
