### PR TITLE
KOGITO-3576 Use artifactId as an example artifact name

### PR DESCRIPTION
**Pull request by sutaakar**
Returning back finalName defiition removed in https://github.com/kiegroup/kogito-examples/pull/387.

Signed-off-by: Karel Suta <ksuta@redhat.com>

JIRA: https://issues.redhat.com/browse/KOGITO-3576

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@rsynek could you take a look?

**Comment by sutaakar** [comment]
jenkins please retest this

**Review by rsynek — APPROVED** [review]

**Comment by sutaakar** [comment]
Test failure not related

**Comment by sutaakar** [comment]
jenkins please retest this

**Pull request merged**
