### PR TITLE
KOGITO-4093 quarkus bump 1.11.0.Beta2 

### PR DESCRIPTION
**Pull request by evacchi**
related https://github.com/kiegroup/kogito-runtimes/pull/956

https://issues.redhat.com/browse/KOGITO-4093

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by evacchi** [comment]
@ricardozanini can you take a look and see what's wrong here, it looks like it's cloud-event related? thx! /cc @tsurdilo  @cristianonicolai @tiagodolphine 

	- Emitter{channel:'kogito_outgoing_stream'} has no downstream
	- OutgoingConnector{channel:'pr_verified', attribute:'mp.messaging.outgoing.pr_verified'} has no upstream

they did change the wiring algorithm https://github.com/quarkusio/quarkus/issues/12486#issuecomment-753792297

EDIT I attempted to fix ~~one of~~ both the broken projects, take a look at the fix (seems to be working locally but don't know what will happen on CI), ~~I can't exactly figure out what's wrong with the github pr flow~~ :)

**Comment by evacchi** [comment]
seems still broken please take a look -- I'll be off tomorrow

**Comment by cristianonicolai** [comment]
@evacchi seems like Quarkus now needs mp settings to be in the test application.properties.

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
