### PR TITLE
Upgrade OptaPlanner to 7.39.0.Final

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Review by evacchi — APPROVED** [review]
there are test failures, not sure if they are related or CI-specific? @radtriste @MarianMacik

**Comment by radtriste** [comment]
```
[INFO] Running org.acme.travel.MessagingIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.337 s <<< FAILURE! - in org.acme.travel.MessagingIT
[ERROR] testProcess  Time elapsed: 0.019 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.KafkaQuarkusTestResource@507187c1
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=confluentinc/cp-kafka:5.2.1, imagePullPolicy=DefaultPullPolicy())
Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for confluentinc/cp-kafka:5.2.1
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: error pulling image configuration: toomanyrequests: Too Many Requests. Please see https://docs.docker.com/docker-hub/download-rate-limit/
```
seems related to our access to Docker

**Comment by evacchi** [comment]
let's respin the wheel

**Comment by ge0ffrey** [comment]
jenkins retest this

**Pull request merged**
