### PR TITLE
FAI-677: Fix dmn-tracing-quarkus

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/FAI-677

This allows me to run the example with a compiled Quarkus image (i.e. not `quarkus:dev`) and Docker composed Kafka, Infinispan and Trusty Service. Furthermore I can access HTTP endpoints for the example's Swagger API ([localhost:8080/q/swagger-ui](http://localhost:8080/q/swagger-ui)) and Trusty Service's API ([localhost:8081/v1/executions](http://localhost:8081/executions) etc). It does not let me running the Dev Services Kafka... but at least one form of execution works.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
```
[2021-11-12T13:50:52.301Z] [INFO] Kogito Example :: DMN Tracing - Quarkus ............ SUCCESS [ 58.271 s]
```

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Hi @Ginxo, IDK if this is something for you to know about?

The Github Action build is failing with:
```
...
Trying to resolve the latest version from remote
Error: certificate has expired
```

**Comment by Ginxo** [comment]
> Hi @Ginxo, IDK if this is something for you to know about?
> 
> The Github Action build is failing with:
> 
> ```
> ...
> Trying to resolve the latest version from remote
> Error: certificate has expired
> ```

This is the first time I see it. Anyway I've reported it https://github.community/t/error-certificate-has-expired-when-executing-composite-actions/212221

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
```
[2021-11-15T10:56:57.655Z] [ERROR] No data of this type found. Use containsData to check for this first.
[2021-11-15T10:56:57.655Z] [INFO] ------------------------------------------------------------------------
[2021-11-15T10:56:57.656Z] [INFO] Reactor Summary for Kogito Example 2.0.0-SNAPSHOT:
[2021-11-15T10:56:57.656Z] [INFO] 
[2021-11-15T10:56:57.656Z] [INFO] Kogito Example ..................................... SUCCESS [  4.379 s]
[2021-11-15T10:56:57.656Z] [INFO] Kogito Example :: Decision Table - Quarkus ......... SUCCESS [ 58.851 s]
[2021-11-15T10:56:57.656Z] [INFO] Kogito Example :: Decision Table - Spring Boot ..... FAILURE [ 11.292 s]
...
[2021-11-15T10:56:57.656Z] [INFO] ------------------------------------------------------------------------
[2021-11-15T10:56:57.656Z] [INFO] BUILD FAILURE
[2021-11-15T10:56:57.656Z] [INFO] ------------------------------------------------------------------------
[2021-11-15T10:56:57.656Z] [INFO] Total time:  01:24 min
[2021-11-15T10:56:57.656Z] [INFO] Finished at: 2021-11-15T05:56:56-05:00
[2021-11-15T10:56:57.656Z] [INFO] ------------------------------------------------------------------------
...
[2021-11-15T10:56:57.657Z] Exception in thread "main" org.kie.kogito.codegen.rules.RuleCodegenError: Errors were generated during the code-generation process:
[2021-11-15T10:56:57.657Z] No data of this type found. Use containsData to check for this first.
[2021-11-15T10:56:57.657Z] 
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.internalGenerate(IncrementalRuleCodegen.java:164)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.core.AbstractGenerator.generate(AbstractGenerator.java:69)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.core.ApplicationGenerator.lambda$generateComponents$0(ApplicationGenerator.java:94)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.core.ApplicationGenerator.generateComponents(ApplicationGenerator.java:96)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.core.ApplicationGenerator.generate(ApplicationGenerator.java:73)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.maven.plugin.GenerateModelMojo.generateModel(GenerateModelMojo.java:99)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.maven.plugin.GenerateModelMojo.execute(GenerateModelMojo.java:70)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[2021-11-15T10:56:57.657Z] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[2021-11-15T10:56:57.657Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-15T10:56:57.657Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-15T10:56:57.657Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-15T10:56:57.657Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-15T10:56:57.657Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[2021-11-15T10:56:57.657Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[2021-11-15T10:56:57.657Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[2021-11-15T10:56:57.657Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[2021-11-15T10:56:57.657Z] Caused by: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
[2021-11-15T10:56:57.657Z] 	at com.github.javaparser.ast.Node.getData(Node.java:505)
[2021-11-15T10:56:57.657Z] 	at com.github.javaparser.ast.CompilationUnit.getPrinter(CompilationUnit.java:154)
[2021-11-15T10:56:57.657Z] 	at com.github.javaparser.ast.Node.lambda$getPrinter$1(Node.java:199)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.Optional.map(Optional.java:265)
[2021-11-15T10:56:57.657Z] 	at com.github.javaparser.ast.Node.getPrinter(Node.java:199)
[2021-11-15T10:56:57.657Z] 	at com.github.javaparser.ast.Node.toString(Node.java:322)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)
[2021-11-15T10:56:57.657Z] 	at org.drools.modelcompiler.builder.PackageModel.generateRulesInUnit(PackageModel.java:680)
[2021-11-15T10:56:57.657Z] 	at org.drools.modelcompiler.builder.PackageModel.lambda$getRulesSource$5(PackageModel.java:568)
[2021-11-15T10:56:57.657Z] 	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
[2021-11-15T10:56:57.657Z] 	at org.drools.modelcompiler.builder.PackageModel.getRulesSource(PackageModel.java:559)
[2021-11-15T10:56:57.657Z] 	at org.drools.modelcompiler.builder.PackageModelWriter.<init>(PackageModelWriter.java:37)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.rules.KogitoPackageSources.dumpSources(KogitoPackageSources.java:68)
[2021-11-15T10:56:57.657Z] 	at org.drools.modelcompiler.builder.ModelBuilderImpl.buildRules(ModelBuilderImpl.java:212)
[2021-11-15T10:56:57.657Z] 	at org.drools.modelcompiler.builder.ModelBuilderImpl.doSecondBuildStep(ModelBuilderImpl.java:117)
[2021-11-15T10:56:57.657Z] 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:115)
[2021-11-15T10:56:57.657Z] 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:99)
[2021-11-15T10:56:57.657Z] 	at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.internalGenerate(IncrementalRuleCodegen.java:158)
[2021-11-15T10:56:57.657Z] 	... 35 more
```

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Review by r00ta — APPROVED** [review]

**Pull request merged**
