### PR TITLE
KOGITO-1712: use kafka.bootstrap.servers.

### PR DESCRIPTION
**Pull request by DuncanDoyle**

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Thanks @DuncanDoyle! @evacchi fyi this one will also fix @tkobayas problem that he reported today in the mail. :)

**Comment by ricardozanini** [comment]
Why? :(

```log
[INFO] Arguments: 

[INFO] Directory: /home/jenkins/workspace/IE_kogito_kogito-examples_PR-184/kogito-apps/node_modules/cypress

[INFO] Output:

[INFO] Installing Cypress (version: 4.3.0)

[INFO] 

[INFO] [12:11:50]  Downloading Cypress     [started]

[INFO] [12:21:50]  Downloading Cypress     [failed]

[INFO] The Cypress App could not be downloaded.

[INFO] 

[INFO] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

[INFO] 

[INFO] Otherwise, please check network connectivity and try again:

[INFO] 

[INFO] ----------

[INFO] 

[INFO] URL: https://download.cypress.io/desktop/4.3.0?platform=linux&arch=x64

[INFO] Error: Corrupted download

[INFO] 

[INFO] Expected downloaded file to have checksum: c2ad1521a91cdec2228b0f855c3f3a7a96210edc2af467877fcf160d97fee87fdc68461a89d905c223f22c4f5638d4489113af703e8fe10dff4a1ac50a84c7e1

[INFO] Computed checksum: 988379aa93a97b28c6f74ce28eb159e0016afa99e663e4ffadf75f1e25b01ae4663b86a701ee650bc3f6e522b3b2e7a204696aea35633ee422ea8a43c33c200b

[INFO] 

[INFO] Expected downloaded file to have size: 170191434

[INFO] Computed size: 19269230
```

**Comment by ricardozanini** [comment]
Can we merge this? Also, @DuncanDoyle please cherry-pick for 0.9.x once we have the Travel Agency there please?

**Comment by cristianonicolai** [comment]
@DuncanDoyle @ricardozanini isn't a bug on Quarkus that it doesn't read the _kafka.bootstrap.servers_ instead, just the server defined in the messaging definition?

**Comment by ricardozanini** [comment]
> @DuncanDoyle @ricardozanini isn't a bug on Quarkus that it doesn't read the _kafka.bootstrap.servers_ instead, just the server defined in the messaging definition?

If we have the messaging definition, Quarkus won't read `kafka.bootstrap.servers`. But if we only have this one, Quarkus will read it for all client/topics in the classloader. See: https://github.com/quarkusio/quarkus/issues/7791

**Review by cristianonicolai — APPROVED** [review]

**Comment by ricardozanini** [comment]
@evacchi could you take a look? We need this for 0.9.1.

**Review by evacchi — APPROVED** [review]

**Pull request merged**
