### PR TITLE
[incubator-kie-issues-1682] Test cases in kogito repos GHA fail with …

### PR DESCRIPTION
**Pull request by tkobayas**
…"pull access denied for vectorized/redpanda"

### Issue:
- https://github.com/apache/incubator-kie-issues/issues/1682

### Cross repo PRs
- https://github.com/apache/incubator-kie-kogito-apps/pull/2162
- https://github.com/apache/incubator-kie-kogito-runtimes/pull/3812
- https://github.com/apache/incubator-kie-kogito-examples/pull/2043 (This one)

---
- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by tkobayas** [comment]
The fix is to overwrite `quarkus.kafka.devservices.image-name` with `container.image.kafka`, which is defined as `redpandadata/redpanda:v24.3.1` in `kogito-build/kogito-build-no-bom-parent/pom.xml` in https://github.com/apache/incubator-kie-kogito-runtimes/pull/3812 , or defined as `redpandadata/redpanda:v24.3.1` in `serverless-workflow-examples-parent/pom.xml` because serverless-workflow-examples don't inherit from kogito-build-no-bom-parent.

I'm not knowledgeable around this area of kogito, just taking care of container image name. Probably there are still failing tests.

Please anyone have a look. Thanks!

**Review by gmunozfe — APPROVED** [review]
Looks good to me, well done @tkobayas 
Probably this won't be needed in the future as Quarkus team has already fixed in their side, but in the meanwhile we can leave it
https://github.com/quarkusio/quarkus/pull/45028

**Review by fjtirado — APPROVED** [review]

**Review by ljmotta — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Comment by yesamer** [comment]
@tkobayas Thank you, I'm going to merge this PR in order to unblock other PRs

**Comment by yesamer** [comment]
@tkobayas Apologies, I just noticed this is a multi-repo PR :'( Shame on me. I'll contact you to understand how to manage this

**Comment by fjtirado** [comment]
@yesamer We do not need to do anything special (so dont worry ;)), I just merged the runtimes, which was ok, and once the apps is green, I will merge that one too

**Pull request merged**
