### PR TITLE
[KOGITO-3914] Fixing SW examples to match spec 0.5

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Depends on: https://github.com/kiegroup/kogito-runtimes/pull/979
See: https://issues.redhat.com/browse/KOGITO-3914

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by ricardozanini** [comment]
It seems an error in the example:

```
2021-01-26 15:25:01,545 ERROR [org.jbp.wor.ins.imp.WorkflowProcessInstanceImpl] (vert.x-eventloop-thread-0) Unexpected error (id e07ab2c5-cff8-489f-80f5-a1885fe79fbb) while executing node VerifyNewApplicant in process instance af6b64f3-6732-46ff-adca-f2ea7994c6d6: org.jbpm.workflow.instance.WorkflowRuntimeException: [applicantworkflow:af6b64f3-6732-46ff-adca-f2ea7994c6d6 - VerifyNewApplicant:7] -- XOR split could not find at least one valid outgoing connection for split VerifyNewApplicant
```

But it's working in the local tests. See image:
Screenshot from 2021-01-26 17-51-08

Maybe something related to the dependant branch not getting updated?

I'll investigate further after the CI from runtimes passes.

**Review by tsurdilo — COMMENTED** [review]
LGTM

we could add the updates to the functionref and transition definitions and do a minor sdk release ;) 
i think that would even more reduce the amount of lines for the json/yaml

**Comment by tsurdilo** [comment]
@ricardozanini just one note if we advertise this to community. We are with this NOT aligning to the 0.5 specification release
as we included the updates to the start/end definitions which are not available in 0.5 spec.

we are here compliant with the 1.0.3.Final SW Java SDK release which means its compliant to 0.5 spec version + addition of start/end definition updates. This change to start/end defs will be part of the spec 0.6 release .Just FYI

**Comment by tsurdilo** [comment]
@ricardozanini if its important that we are aligning with 0.5 spec version, I would suggest excluding the changes to start/end definitions ( here and in the tests in the engine pr), as its backwards compatible from the sdk point of view. 

Then we can with confidence say its compliant with 0.5 spec  release :)

**Comment by ricardozanini** [comment]
@tsurdilo, I think we can keep the start/end definitions and align the speech since we will have to update them anyway, right? Plus, it took me a lot of work to change everything. :cry:

**Comment by ricardozanini** [comment]
Jenkins retest this please

**Comment by ricardozanini** [comment]
@evacchi, if this is PR is fine to you, can you please merge?

**Review by evacchi — APPROVED** [review]

**Pull request merged**
