### PR TITLE
Disable an unstable test

### PR DESCRIPTION
**Pull request by rsynek**
Please see https://issues.redhat.com/browse/KOGITO-5664. As a temporary solution, I am proposing disabling the test until it's fixed.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by rsynek** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by cristianonicolai** [comment]
@rsynek should also disable the one in process-kafka-multi-springboot  ?

**Comment by rsynek** [comment]
@cristianonicolai does that one fail too? I haven't noticed in the OptaPlanner downstream build. Ok, let me disable it too.

**Review by tiagodolphine — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by tiagodolphine** [comment]
Jenkins rerun examples tests

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
