### PR TITLE
KOGITO-3685: Avoid to compile native images twice

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3685
Description: the quarkus maven build was configured to run in different goals. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by Sgitario** [comment]
I did checked that the native is now built only once and the native tests are being executed.

**Review by tarilabs — COMMENTED** [review]
Thank you I run a partial test locally and confirm this solves, but I must admit I have not understood why removing `<goal>native-image</goal>` from the parent pom is the fix. Could you explain it, please?
Anyhow thanks again

**Review by radtriste — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
LGTM

**Comment by Sgitario** [comment]
> Thank you I run a partial test locally and confirm this solves, but I must admit I have not understood why removing `<goal>native-image</goal>` from the parent pom is the fix. Could you explain it, please?
> Anyhow thanks again

It seems that we were still using the legacy way to build native images (using the goal "native-image" which [is deprecated](https://github.com/quarkusio/quarkus/blame/master/devtools/maven/src/main/java/io/quarkus/maven/NativeImageMojo.java)) and also using the quarkus.package.type=native property.

**Comment by tarilabs** [comment]
@Sgitario thank you for taking the time to explaining it to me,
so I understand we are now relying on this: 
https://github.com/kiegroup/kogito-examples/blob/d536c26b2163a871d69d70a39ba92f2a88022def/pom.xml#L246
instead of the old/deprecated
`<goal>native-image</goal>`

👍

**Comment by Sgitario** [comment]
jenkins please retest this

**Comment by Sgitario** [comment]
I think this PR is ready to be merged, can you proceed @danielezonca ? Thanks!

**Pull request merged**
