### PR TITLE
Fix "java.lang.IllegalStateException: Illegal access: this web applic…

### PR DESCRIPTION
**Pull request by tkobayas**
…ation instance has been stopped already." by SpringBootTest in Spring Boot 3

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
```
2023-12-01T15:21:07.502+09:00  INFO 104911 --- [0-auto-2-exec-1] o.a.c.loader.WebappClassLoaderBase       : Illegal access: this web application instance has been stopped already. Could not load [IndexFile.pmml_json]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.

java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [IndexFile.pmml_json]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1457) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1047) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
	at org.kie.internal.utils.CompositeClassLoader.getResource(CompositeClassLoader.java:151) ~[kie-internal-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403) ~[na:na]
	at org.kie.efesto.common.api.utils.MemoryFileUtils.getFileByFileNameFromClassloader(MemoryFileUtils.java:63) ~[efesto-common-api-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
	at org.kie.efesto.common.api.io.IndexFile.findIndexFilesFromClassLoader(IndexFile.java:179) ~[efesto-common-api-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
	at org.kie.efesto.runtimemanager.core.model.EfestoRuntimeContextImpl.populateGeneratedResourcesMap(EfestoRuntimeContextImpl.java:64) ~[efesto-runtime-manager-core-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
	at org.kie.efesto.runtimemanager.core.model.EfestoRuntimeContextImpl.<init>(EfestoRuntimeContextImpl.java:46) ~[efesto-runtime-manager-core-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
	at org.kie.efesto.runtimemanager.core.model.EfestoRuntimeContextUtils.buildWithParentClassLoader(EfestoRuntimeContextUtils.java:33) ~[efesto-runtime-manager-core-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
	at org.kie.dmn.core.pmml.DMNKiePMMLTrustyInvocationEvaluator.getEfestoRuntimeContext(DMNKiePMMLTrustyInvocationEvaluator.java:209) ~[kie-dmn-core-9.45.0-SNAPSHOT.jar:9.45.0-SNAPSHOT]
```
The IllegalStateException means Spring Boot 3 is more strict about using parent classloader (`WebappClassLoaderBase`) which was used in the previous test. On the other hand, kogito holds `DMNRuntime` (including the parent classloader) in a static field https://github.com/apache/incubator-kie-kogito-runtimes/blob/quarkus-3.2LTS/drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/AbstractDecisionModels.java#L41

`<reuseForks>false</reuseForks>` (= use a different JVM process per test) simply cleans up the classloader issue and solves the test failure. Of course, it has some overhead, but it doesn't seem to be a lot.

@gitgabrio is this an acceptable solution?

**Review by mariofusco — APPROVED** [review]

**Comment by gitgabrio** [comment]
Thanks @tkobayas !

**Review by gitgabrio — APPROVED** [review]
Thanks LGTM!

**Comment by tkobayas** [comment]
@mariofusco Please merge, thanks!

**Pull request merged**
