### PR TITLE
Creating new profile from openvino example

### PR DESCRIPTION
**Pull request by fjtirado**
This will prevent huge image (this example requires a lot of python libraries)

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Then we have to run a separate pipeline to validate the Python use case?

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1825 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1825/1/display/redirect

**Test results:**
- PASSED: 376
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1825/1/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [8083, 57631] should be listening)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1825/1/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [8083, 57679] should be listening)
</details>

**Comment by ricardozanini** [comment]
@wmedvede @fjtirado This `OutboxIT` test serves for what purpose? This test has been failing from the beginning of time. I think we should either remove it or solve this flaky test for once.

**Comment by jstastny-cz** [comment]
> @wmedvede @fjtirado This `OutboxIT` test serves for what purpose? This test has been failing from the beginning of time. I think we should either remove it or solve this flaky test for once.

+1 , that one is unstable even in my dind image attempts, so does not seem to be env port conflict or sth.

**Comment by wmedvede** [comment]
> @wmedvede @fjtirado This `OutboxIT` test serves for what purpose? This test has been failing from the beginning of time. I think we should either remove it or solve this flaky test for once.

IDK, as you said, it looks like this test has been failing from the beginning of time, and nobody has ever used it. I'll take a look, maybe it's time to remove it.

**Comment by ricardozanini** [comment]
Thanks @wmedvede. Let's remove/disable it and open a kie-issue to track it down. If someone asks, we can point to the issue and the person can fix the test.

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Pull request merged**
