### PR TITLE
[1.7.x] update trusty images to 1.7

### PR DESCRIPTION
**Pull request by r00ta**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by r00ta** [comment]
Jenkins retest this please

**Review by radtriste — APPROVED** [review]

**Comment by r00ta** [comment]
Can we merge this one? The trusty demonstration contains only documentation (i.e. no tests) and the CI is failing for some other reasons

**Comment by manstis** [comment]
Does the failure not suggest something quite seriously wrong somewhere:
```
[2021-05-17T12:49:38.926Z] Expected: a collection containing "dmn-drools-quarkus-metrics:2.0.0-SNAPSHOT - hello - Operational Dashboard"
[2021-05-17T12:49:38.926Z]   Actual: <[dmn-drools-quarkus-metrics:1.7.0-SNAPSHOT - Hello - Domain Dashboard, dmn-drools-quarkus-metrics:1.7.0-SNAPSHOT - hello - Operational Dashboard, dmn-drools-quarkus-metrics:1.7.0-SNAPSHOT - LoanEligibility - Domain Dashboard, dmn-drools-quarkus-metrics:1.7.0-SNAPSHOT - LoanEligibility - Operational Dashboard]>
```
The difference appears to be the version numbers. Was this PR rebased with `master` before the build failed?

Is it plausible there has been a version change to `2.0.0-SNAPSHOT` _somewhere_ but it has not been applied across all affected repositories and/or modules... I think this type of failure deserves an email to BSIG.

**Comment by radtriste** [comment]
I certainly think that this test needs to be corrected as we are here on branch 1.7.x and so the version is NOT 2.0.0-SNAPSHOT.
Indeed it deserves a mail to bsig or to the creator of the test...

**Comment by radtriste** [comment]
@r00ta can you have a look to those tests ? I think you set them up ;)
https://github.com/kiegroup/kogito-examples/blob/1.7.x/dmn-drools-quarkus-metrics/src/test/java/org/kie/kogito/examples/GrafanaDockerComposeIT.java#L106-L109

**Comment by r00ta** [comment]
Hi @radtriste @manstis , now the dashboards will contain the information about the maven GAV. i.e. the name of the dashboard is like `<artifactId>-<version>-name`. And of course when we branch the release this information change and we have to update the tests. Thanks for spotting it, I need to understand how to fix it properly now..

**Comment by r00ta** [comment]
See here for the quick fix. I'll think about the real fix in the upcoming days https://github.com/kiegroup/kogito-examples/pull/701

**Comment by radtriste** [comment]
thx ! do you have a follow-up issue for this ?

**Comment by r00ta** [comment]
fyi https://issues.redhat.com/browse/KOGITO-5163

**Pull request merged**
