### PR TITLE
[KOGITO-2832] Support process-infinispan-persistence-quarkus on macOS running docker desktop

### PR DESCRIPTION
**Pull request by lucamolteni**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

https://issues.redhat.com/browse/KOGITO-2832

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by lucamolteni** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
BEFORE being stuck and hanging at:
image

AFTER working fine on macOS
image

**Review by tarilabs — APPROVED** [review]
can confirm working locally see https://github.com/kiegroup/kogito-examples/pull/305#issuecomment-661939381

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
I remember seeing this property in DataIndex as well.

**Review by danielezonca — APPROVED** [review]
Thanks for the PR! Approving 👍

**Pull request merged**
