### PR TITLE
[KOGITO-5932] Implementing custom-metrics generation examples

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @evacchi @jiripetrlik

See 
https://issues.redhat.com/browse/KOGITO-5932

Examples related

Depends on https://github.com/kiegroup/kogito-runtimes/pull/1750

### CODE REVIEW

**Review by jiripetrlik — APPROVED** [review]

**Review by danielezonca — COMMENTED** [review]
Can you please integrate custom metric in the existing [`dmn-drools-quarkus-metrics`](https://github.com/kiegroup/kogito-examples/tree/stable/dmn-drools-quarkus-metrics) example using a listener (see [`dmn-listener-quarkus`](https://github.com/kiegroup/kogito-examples/tree/stable/dmn-listener-quarkus))?
Same for SpringBoot
Then update README to describe it

**Comment by gitgabrio** [comment]
@danielezonca 
Could you please take a look again, eventually approving/merge ? Thanks

**Comment by gitgabrio** [comment]
@kiegroup/gatekeepers

Could you please merge this, squashing commits? Thanks!

**Review by danielezonca — APPROVED** [review]

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Pull request merged**
