### PR TITLE
add GITHUB_TOKEN to build-chain GHA wrokflows

### PR DESCRIPTION
**Pull request by Ginxo**
Related PRs:

- https://github.com/kiegroup/kogito-runtimes/pull/1677
- https://github.com/kiegroup/kogito-examples/pull/954
- https://github.com/kiegroup/kogito-apps/pull/1078

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by danielezonca — COMMENTED** [review]
You need to target `main` branch and not `stable`

**Comment by Ginxo** [comment]
> You need to target `main` branch and not `stable`

@danielezonca thanks! done!

**Comment by ricardozanini** [comment]
```
Definition file https://raw.githubusercontent.com/${GROUP}/kogito-pipelines/${BRANCH}/.ci/pull-request-config.yaml does not exist for any case
```
Is this variable valid?

**Comment by Ginxo** [comment]
> ```
> Definition file https://raw.githubusercontent.com/${GROUP}/kogito-pipelines/${BRANCH}/.ci/pull-request-config.yaml does not exist for any case
> ```
> 
> Is this variable valid?

@ricardozanini it is... `GROUP`, `BRANCH` and `PROJECT_NAME` are placeholders treated by build-chain see https://github.com/kiegroup/github-action-build-chain#input-fields
will try:

1. source group and branch
2. target group and source branch
3. target group and branch

It will take the first existing one.

**Comment by domhanak** [comment]
Closing as outdated

**Pull request closed without merging**
