### PR TITLE
KOGITO-6396 - Non unique test case IDs in process-kafka-* examples

### PR DESCRIPTION
**Pull request by MarianMacik**
[KOGITO-6396](https://issues.redhat.com/browse/KOGITO-6396)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]
Seems GitHub got it wrong, we're not renaming the maven modules here. The changes are being mixed between 2 examples.

**Review by jomarko — COMMENTED** [review]
Thank you @MarianMacik. The changes seems to be on proper places to me, however causing one inconsistency I think. If we check `README.md` of particular `process-kafka-*` projects, we will find out some screenshots, especially Input/Output popup related, now refers to non existing classes. 

I spot the same issue in my #1016 and then I decided to open just #1019.

Not sure what is the best solution we want to keep this package names refactoring. Ideas I have:
- remove problematic screenshots completely, as maintaining screenshots in documentation is always an overhead. it should be done with every UI update.
- remove problematic screenshots but provide at least some textual, tabular description, what is nice as gives a copy and paste possibility when someone takes README as an tutorial.

**Review by jomarko — APPROVED** [review]
Approved after private GChat discussion

**Comment by MarianMacik** [comment]
@jomarko Changed only packages of test classes, as agreed.

**Comment by jomarko** [comment]
@MarianMacik thank you, my approval still holds true.

**Comment by MarianMacik** [comment]
Jenkins retest this

**Pull request merged**
