### PR TITLE
[KOGITO-2607] Adding example for SWF compensation

### PR DESCRIPTION
**Pull request by fjtirado**
Depends on https://github.com/kiegroup/kogito-runtimes/pull/1732

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Review by tiagodolphine — COMMENTED** [review]
LGTM, maybe it is worth adding a native test to CompensationRestIT.

**Comment by fjtirado** [comment]
> LGTM, maybe it is worth adding a native test to CompensationRestIT.

Sure, added ;)

**Review by tiagodolphine — APPROVED** [review]

**Comment by fjtirado** [comment]
jenkins rerun kogito-examples tests

**Review by ricardozanini — APPROVED** [review]
Simple and powerful example! Loved the `jq` expressions. 😎

**Pull request merged**
