### PR TITLE
[1.13.x] [KOGITO-6425] - Update Quarkus Messaging HTTP dependency for Quarkus …

### PR DESCRIPTION
**Pull request by MarianMacik**
…2.7.x

[KOGITO-6425](https://issues.redhat.com/browse/KOGITO-6425)

@fjtirado I tagged you as Zanini is not here now :)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#21` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 413
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/21/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:104)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/21/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:95)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/21/testReport/org.acme.travel/MessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MessagingIT.testProcess(MessagingIT.java:109)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/21/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.kie.kogito.examples.demo.OutboxIT was not fulfilled within 4 minutes  10 seconds.<br/>	at org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents(OutboxIT.java:70)<br/>Caused by: java.net.ConnectException: Connection refused (Connection refused)<br/>	at org.kie.kogito.examples.demo.OutboxIT.lambda$testSendProcessEvents$0(OutboxIT.java:74)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/21/display/redirect

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#22` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 416
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/22/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
java.lang.IllegalStateException: Failed to load ApplicationContext<br/>Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demo.orderItems' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-outbox-mongodb-springboot/target/classes/org/kie/kogito/examples/OrderItemsProcess.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.kie.kogito.examples.OrderItemsProcess]: Constructor threw exception; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='debezium', source='admin', password=<hidden>, mechanismProperties=<hidden>}<br/>Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.kie.kogito.examples.OrderItemsProcess]: Constructor threw exception; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='debezium', source='admin', password=<hidden>, mechanismProperties=<hidden>}<br/>Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='debezium', source='admin', password=<hidden>, mechanismProperties=<hidden>}<br/>Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server localhost:49212. The full response is {"operationTime": {"$timestamp": {"t": 1646735146, "i": 9}}, "ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1646735146, "i": 9}}, "signature": {"hash": {"$binary": {"base64": "WQRHZGYUoaXQdt3ywWH1dGeWH1M=", "subType": "00"}}, "keyId": 7072673597243785222}}}<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/22/display/redirect

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#23` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 416
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/23/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.kie.kogito.examples.demo.OutboxIT was not fulfilled within 4 minutes  10 seconds.<br/>	at org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents(OutboxIT.java:70)<br/>Caused by: java.net.ConnectException: Connection refused (Connection refused)<br/>	at org.kie.kogito.examples.demo.OutboxIT.lambda$testSendProcessEvents$0(OutboxIT.java:74)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/23/display/redirect

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#24` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 414
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/24/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:104)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/24/testReport/org.acme.travel/MessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MessagingIT.testProcess(MessagingIT.java:109)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/24/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
java.lang.IllegalStateException: Failed to load ApplicationContext<br/>Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demo.orderItems' defined in file [/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/process-outbox-mongodb-springboot/target/classes/org/kie/kogito/examples/OrderItemsProcess.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.kie.kogito.examples.OrderItemsProcess]: Constructor threw exception; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='debezium', source='admin', password=<hidden>, mechanismProperties=<hidden>}<br/>Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.kie.kogito.examples.OrderItemsProcess]: Constructor threw exception; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='debezium', source='admin', password=<hidden>, mechanismProperties=<hidden>}<br/>Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='debezium', source='admin', password=<hidden>, mechanismProperties=<hidden>}<br/>Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server localhost:49212. The full response is {"operationTime": {"$timestamp": {"t": 1646745613, "i": 1}}, "ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1646745613, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "RfXnydStu9P6tGpsKYUMCbzQZcU=", "subType": "00"}}, "keyId": 7072718531191635974}}}<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/24/display/redirect

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#25` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 415
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/25/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:104)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/25/testReport/org.kie.kogito.examples.demo/OutboxIT/testSendProcessEvents/">org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.kie.kogito.examples.demo.OutboxIT was not fulfilled within 4 minutes  10 seconds.<br/>	at org.kie.kogito.examples.demo.OutboxIT.testSendProcessEvents(OutboxIT.java:70)<br/>Caused by: java.net.ConnectException: Connection refused (Connection refused)<br/>	at org.kie.kogito.examples.demo.OutboxIT.lambda$testSendProcessEvents$0(OutboxIT.java:74)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/25/display/redirect

**Review by fjtirado — APPROVED** [review]

**Comment by MarianMacik** [comment]
tests are not related, but will try once more :)

Jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#26` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 414
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/26/testReport/org.acme.travel/MultiMessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:104)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/26/testReport/org.acme.travel/MessagingIT/Build_projects___testProcess/">Build projects / org.acme.travel.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.MessagingIT.testProcess(MessagingIT.java:109)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/26/testReport/org.kogito.serverless.examples/ApplicantWorkflowIT/testApplicantProcess/">org.kogito.serverless.examples.ApplicantWorkflowIT.testApplicantProcess</a></summary>
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.kogito.serverless.examples.ApplicantWorkflowIT that uses java.util.List was not fulfilled within 10 seconds.<br/>	at org.kogito.serverless.examples.ApplicantWorkflowIT.testApplicantProcess(ApplicantWorkflowIT.java:71)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-examples.tests.kogito-examples/26/display/redirect

**Comment by MarianMacik** [comment]
Jenkins retest this

**Pull request merged**
