### PR TITLE
KOGITO-5667 Split Quarkus and Spring Boot specific test-utils in diff…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…erent modules

Assembly:
- https://github.com/kiegroup/kogito-examples/pull/840
- https://github.com/kiegroup/kogito-apps/pull/976
- https://github.com/kiegroup/kogito-runtimes/pull/1510

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by ricardozanini — COMMENTED** [review]
I think it's worth adding these new dependencies to Spring Boot and Quarkus BOM dependencies management section with the test scope as well. Or even as a direct dependency with test scope. Won't hurt the final user jar. wdyt?

**Comment by danielezonca** [comment]
> I think it's worth adding these new dependencies to Spring Boot and Quarkus BOM dependencies management section with the test scope as well. Or even as a direct dependency with test scope. Won't hurt the final user jar. wdyt?

My suggestion is to avoid defining the scope at bom/dependencyManagement level because it can lead to strange behaviours (i.e. [link](https://stackoverflow.com/a/20750041)). I had a similar issue in some previous PR with a dependency declared with `test` scope. My suggestion is to not worry about the scope, the dependency is clearly mentioning `test` both in the name of the artifact and in the package and if a user wants to extend it in some way we should not prevent it.
At least this is my PoV :)

**Comment by ricardozanini** [comment]
jenkins rerun examples tests

**Comment by ricardozanini** [comment]
jenkins rerun examples tests

**Pull request merged**
