### PR TITLE
KOGITO-4223 Kogito SB archetype fail Swagger/OAS ootb

### PR DESCRIPTION
**Pull request by tarilabs**
See https://github.com/kiegroup/kogito-runtimes/pull/996

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by tarilabs** [comment]
A few examples...

# dmn-springboot-example

## BEFORE

Screenshot 2021-01-22 at 11 27 17

## AFTER

Screenshot 2021-01-22 at 11 30 09

**Comment by tarilabs** [comment]
# decisiontable-springboot-example

## BEFORE

Screenshot 2021-01-22 at 11 40 07

## AFTER

Screenshot 2021-01-22 at 11 43 19

**Comment by tarilabs** [comment]
# process-springboot-example

## BEFORE

Screenshot 2021-01-22 at 11 45 39

## AFTER

Screenshot 2021-01-22 at 11 46 46

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
```

[INFO] ------------------------------------------------------------------------

[INFO] Reactor Summary for Kogito Example 2.0.0-SNAPSHOT:

[INFO] 

[INFO] Kogito Example ..................................... SUCCESS [  3.397 s]

[INFO] Kogito Example :: Decision Table - Quarkus ......... SUCCESS [ 25.686 s]

[INFO] Kogito Example :: Decision Table - Spring Boot ..... SUCCESS [ 18.510 s]

[INFO] Kogito Example :: DMN with listeners - Quarkus ..... SUCCESS [ 20.711 s]

[INFO] Kogito Example :: DMN with listeners - Spring Boot . SUCCESS [ 13.261 s]

[INFO] Kogito Example :: DMN :: PMML ...................... SUCCESS [ 29.214 s]

[INFO] Kogito Example :: DMN :: PMML - Spring Boot ........ SUCCESS [ 20.472 s]

[INFO] Kogito Example :: DMN .............................. SUCCESS [ 22.288 s]

[INFO] Kogito Example :: DMN Metrics Quarkus .............. SUCCESS [ 58.471 s]

[INFO] Kogito Example :: DMN Metrics SpringBoot ........... SUCCESS [ 36.486 s]

[INFO] Kogito Example :: DMN - Spring Boot ................ SUCCESS [ 11.304 s]

[INFO] Kogito Example :: DMN Tracing - Quarkus ............ FAILURE [ 47.357 s]

[INFO] Kogito Example :: DMN Tracing - Spring Boot ........ FAILURE [ 22.404 s]

[INFO] Kogito Example :: Flexible Process - Quarkus ....... SUCCESS [ 23.972 s]

[INFO] Kogito Example :: Flexible process with Spring Boot  SUCCESS [ 11.710 s]

[INFO] Kogito Example :: Travel Agency .................... SUCCESS [  0.027 s]

[INFO] Kogito Example :: Travel Agency :: Basic ........... SUCCESS [ 18.690 s]

[INFO] Kogito Example :: Travel Agency :: Extended ........ SUCCESS [  0.029 s]

[INFO] Kogito Example :: Travel Agency :: Travels ......... SUCCESS [ 55.320 s]

[INFO] Kogito Example :: Travel Agency :: Visas ........... SUCCESS [  7.881 s]

[INFO] Kogito Example :: Onboarding Example ............... SUCCESS [  0.028 s]

[INFO] Kogito Example :: Onboarding Example :: HR with Drools SUCCESS [ 19.165 s]

[INFO] Kogito Example :: Onboarding Example :: Payroll with DMN SUCCESS [ 20.954 s]

[INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Quarkus SUCCESS [ 20.337 s]

[INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Spring Boot SUCCESS [ 10.742 s]

[INFO] Kogito Example :: PMML ............................. SUCCESS [ 25.019 s]

[INFO] Kogito Example :: PMML - Spring Boot ............... SUCCESS [ 15.443 s]

[INFO] Kogito Example :: Process Business Rules Quarkus ... SUCCESS [ 16.765 s]

[INFO] Kogito Example :: Process Business Rules Spring Boot SUCCESS [  9.343 s]

[INFO] Kogito Example :: Process Infinispan Persistence Quarkus SUCCESS [ 31.170 s]

[INFO] Kogito Example :: Process Infinispan Persistence Spring Boot SUCCESS [ 23.229 s]

[INFO] Kogito Example :: Process with Kafka and Quarkus ... SUCCESS [ 32.418 s]

[INFO] Kogito Example :: Process with Kafka and Spring Boot SUCCESS [ 21.586 s]

[INFO] Kogito Example :: Process with Knative Eventing and Quarkus SUCCESS [ 28.526 s]

[INFO] Kogito Example :: Process MongoDB Persistence Quarkus SUCCESS [ 33.636 s]

[INFO] Kogito Example :: Process MongoDB Persistence Spring Boot SUCCESS [ 19.804 s]

[INFO] Kogito Example :: Process, OptaPlanner and Quarkus . SUCCESS [ 34.638 s]

[INFO] Kogito Example :: Process, OptaPlanner and Spring Boot SUCCESS [ 20.237 s]

[INFO] Kogito Example :: Process and Quarkus .............. SUCCESS [ 26.479 s]

[INFO] Kogito Example :: Process and Spring Boot .......... SUCCESS [ 16.331 s]

[INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 16.540 s]

[INFO] Kogito Example :: Process Scripts With Spring Boot . SUCCESS [  7.812 s]

[INFO] Kogito Example :: Process Service Calls with Quarkus SUCCESS [ 16.593 s]

[INFO] Kogito Example :: Process Service Calls with Spring Boot SUCCESS [  9.743 s]

[INFO] Kogito Example :: Process Service Rest Cal with Quarkus SUCCESS [  7.756 s]

[INFO] Kogito Example :: Process Service Rest Call Spring Boot SUCCESS [  4.376 s]

[INFO] Kogito Example :: Process Timer with Quarkus ....... SUCCESS [  5.297 s]

[INFO] Kogito Example :: Process Timer With Spring Boot ... SUCCESS [  2.894 s]

[INFO] Kogito Example :: Process Usertasks With Custom Lifecycle SUCCESS [ 17.574 s]

[INFO] Kogito Example :: Process Usertasks With Custom Lifecycle Spring Boot SUCCESS [  9.465 s]

[INFO] Kogito Example :: Process with Usertasks Quarkus ... SUCCESS [ 16.860 s]

[INFO] Kogito Example :: Process with Usertasks Spring Boot SUCCESS [  9.743 s]

[INFO] Kogito Example :: Process Usertasks With Security OIDC Keycloak Quarkus SUCCESS [ 56.751 s]

[INFO] Kogito Example :: Process Usertasks With Security OIDC Spring Boot SUCCESS [ 49.360 s]

[INFO] Kogito Example :: Process Usertasks With Security Quarkus SUCCESS [ 21.835 s]

[INFO] Kogito Example :: Process Usertasks With Security Spring Boot SUCCESS [ 15.616 s]

[INFO] Kogito Example :: Rules HelloWorld ................. SUCCESS [ 19.598 s]

[INFO] Kogito Example :: RuleUnit - Quarkus ............... SUCCESS [ 21.260 s]

[INFO] Kogito Example :: RuleUnit - Spring Boot ........... SUCCESS [ 10.532 s]

[INFO] Kogito Example :: Serverless Workflow Greeting :: Quarkus SUCCESS [  5.279 s]

[INFO] Kogito Example :: Serverless Workflow Greeting :: Spring Boot SUCCESS [ 10.156 s]

[INFO] Kogito Example :: Serverless Workflow Service Calls :: Quarkus SUCCESS [ 19.143 s]

[INFO] Kogito Example :: Serverless Workflow Service Calls :: Spring Boot SUCCESS [  8.976 s]

[INFO] Kogito Example :: Serverless Workflow Events :: Quarkus SUCCESS [ 33.968 s]

[INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus SUCCESS [ 20.832 s]

[INFO] Kogito Example :: Serverless Workflow Functions And Events :: Quarkus SUCCESS [ 24.870 s]

[INFO] Kogito Example :: Serverless Workflow Github Showcase SUCCESS [  0.026 s]

[INFO] Kogito Example :: Serverless Workflow Github Showcase :: PR Checker Workflow SUCCESS [ 24.373 s]

[INFO] Kogito Example :: Serverless Workflow Github Showcase :: GitHub Service SUCCESS [ 12.785 s]

[INFO] Kogito Example :: Serverless Workflow Github Showcase :: Notification Service SUCCESS [  7.138 s]

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  22:43 min

[INFO] Finished at: 2021-01-23T11:43:40-05:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project dmn-tracing-quarkus: Some files do not have the expected license header -> [Help 1]

[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project dmn-tracing-springboot: Some files do not have the expected license header -> [Help 1]
```

It seems to me the build plugin is enforcing a check which to my knowledge is actually NOT required 🤦

**Comment by tarilabs** [comment]
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 19.028 s <<< FAILURE! - in org.kie.kogito.examples.GrafanaDockerComposeIT
[ERROR] testKogitoContainerIsDeployedAndResponsive  Time elapsed: 1.979 s  <<< ERROR!
org.apache.http.NoHttpResponseException: localhost:8080 failed to respond
	at org.kie.kogito.examples.GrafanaDockerComposeIT.testKogitoContainerIsDeployedAndResponsive(GrafanaDockerComposeIT.java:95)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   GrafanaDockerComposeIT.testKogitoContainerIsDeployedAndResponsive:95 » NoHttpResponse
[INFO] 
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- license-maven-plugin:3.0:check (default) @ dmn-drools-springboot-metrics ---
```

🤷‍♂️ 🎱 

Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins retest this

**Pull request merged**
