### PR TITLE
[0.9.x][KOGITO-1854] Renaming final artifacts to match documentation require…

### PR DESCRIPTION
**Pull request by ricardozanini**
…ments

Chery-pick for: https://github.com/kiegroup/kogito-examples/pull/217

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

### CODE REVIEW

**Review by cristianonicolai — COMMENTED** [review]
@ricardozanini why not keep kogito-visas and kogito-travels?

**Comment by radtriste** [comment]
I would say to have consistency between folder's name and project's name

**Review by radtriste — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Comment by jstastny-cz** [comment]
is this part of any demo that could be affected by the change?

Plus one statement, probably not important this late - other examples got rid of the {version} in resulting artifact, which is quite useful in readmes and docs.

**Comment by ricardozanini** [comment]
> is this part of any demo that could be affected by the change?
> 
> Plus one statement, probably not important this late - other examples got rid of the {version} in resulting artifact, which is quite useful in readmes and docs.

Yeah, I though about that, but since @sterobin already have their PR in place, I'd stayed in the "safe side". I can send a PR to fix that later on master.

Regarding the demos, I verified in my own env and in the master PR, @radtriste also did the check and it's ok.

**Comment by cristianonicolai** [comment]
> I would say to have consistency between folder's name and project's name

yep that would need to be adjusted as well. anyway, not a blocker

**Review by cristianonicolai — APPROVED** [review]

**Review by evacchi — APPROVED** [review]

**Pull request merged**
