### PR TITLE
KOGITO-1155: Examples from 'kiegroup/kogito-examples' include namespaces from other vendors

### PR DESCRIPTION
**Pull request by danielzhe**
Examples recreated from scratch with our tool.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by tarilabs** [comment]
no need, as long as test are passing that is fine 👍

**Comment by ricardozanini** [comment]
@tarilabs I don't have access to the Jenkins from where I am, but I'm seeing that it has failed. Is it tests related? @danielzhe could you please take a look? Many thanks!!

**Comment by danielzhe** [comment]
Jenkins please retest this

**Comment by danielzhe** [comment]
Hi, @ricardozanini. I'm checking, but I still have no idea. I just recreated the .dmn from scratch using VS Code. The previous .dmn file that we had was created with a tool from another vendor.

**Comment by danielzhe** [comment]
@ricardozanini @tarilabs Well, I'm getting the same error on master. So I don't think it's related to this 
PR:
[ERROR] /C:/Dev/kogito-examples/onboarding-example/payroll/target/generated-sources/kogito/org/kie/kogito/examples/Application.java:[46,470] illegal escape character

**Comment by tarilabs** [comment]
> I'm getting the same error on master

I opened the Jenkins and I cannot find occurences of "illegal escape character"
So why do you say it's the same error?
How were you able to reproduce the problem, which on Jenkins appears to be a 404 ?
Considering the problem is Applicaiton within the same example, I believe there is relation, the difficulty will be nowto understand what's actually going wrong.

**Comment by danielzhe** [comment]
@tarilabs I builded from master and get the same error I get building from my PR.

**Comment by danielzhe** [comment]
@tarilabs Ok, I think I found the issue. I'm updating the PR. Thanks!

**Comment by tarilabs** [comment]
it's the MOdel `name`

**Comment by tarilabs** [comment]
the new Model files have changed the name if compared to the original ones, hence the REST endpoint changes, that _also_ explains the 404.

So either the new Model files get the same name as the old ones, or the process definition shall reflect the new Model names.

**Comment by danielzhe** [comment]
Looks like I've found an issue with default output value. :(

**Comment by tarilabs** [comment]
Indeed it looks like you missed to model this:
https://github.com/kiegroup/kogito-examples/pull/132/files#diff-e41b935d76170aa0c1e85cada930b031L59-L61
in the new DMN Model

**Comment by danielzhe** [comment]
@tarilabs It's a new issue. I added manually to the file and I'm opening a JIRA to cover this issue with default output.

**Comment by ricardozanini** [comment]
Good to go? If so, @danielzhe could you please squash your commits? Many thanks!

**Review by evacchi — APPROVED** [review]
as long as everything work as intended, fine for me

**Comment by danielzhe** [comment]
@ricardozanini Done.

**Comment by danielzhe** [comment]
@ricardozanini This is ready to be merged. Thank you!

**Pull request merged**
