### PR TITLE
[KOGITO-4823] Fix README for fast-jar

### PR DESCRIPTION
**Pull request by tkobayas**
https://issues.redhat.com/browse/KOGITO-4823

Now kogito-examples generates fast-jar (target/quarkus-app/quarkus-run.jar) instead of runner jar.

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
 -> sorry, this PR contains a very minor typo in dmn-event-driven-springboot/README.md as well.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>
</details>

### CODE REVIEW

**Review by r00ta — COMMENTED** [review]
Hey @tkobayas thank you so much! Could you double check if the READMEs in `serverless-workflow-temperature-conversion/multiplication-service` and `serverless-workflow-temperature-conversion/subtraction-service` need an update as well?

**Comment by tkobayas** [comment]
Thank you for pointing them out @r00ta . Yes, I have updated.

**Comment by r00ta** [comment]
Hey @tkobayas , see https://github.com/tkobayas/kogito-examples/pull/1

**Comment by tkobayas** [comment]
> Hey @tkobayas , see [tkobayas#1](https://github.com/tkobayas/kogito-examples/pull/1)

Thanks, @r00ta  . But the 2 lines you changed in https://github.com/tkobayas/kogito-examples/pull/1 are in the explanation of building a uber-jar explicitly with `-Dquarkus.package.type=uber-jar`. So the original docs are correct to refer `runner.jar`. Could you confirm?

**Comment by r00ta** [comment]
Wops! My bad :) Thank you @tkobayas !

**Review by r00ta — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
