### PR TITLE
[KOGITO-3297] Add index-dependency for tests

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

Related to kiegroup/kogito-runtimes#750
Fix https://issues.redhat.com/browse/KOGITO-3297

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
CI error does not seem to be related.

**Comment by ruromero** [comment]
jenkins retest this

**Review by ricardozanini — APPROVED** [review]

**Review by evacchi — APPROVED** [review]
i recall some issue with native image + cloud event SDK, can you check that that won't break with some example on kogito-example?

**Comment by ruromero** [comment]
@evacchi can you be a bit more specific about which example or what problem?
I have used this sdk with native image in several places. See https://github.com/cloudevents/sdk-java/tree/master/examples/restful-ws-quarkus

**Pull request merged**
