### PR TITLE
KOGITO-1544: Move kogito-travel-agency-tutorial to kogito-examples (backport)

### PR DESCRIPTION
**Pull request by evacchi**
This is the backported + cherry-picked version of #178 
it can be squashed if preferred (it depends whether we want to retain history on 0.9.x branch too)

### CODE REVIEW

**Comment by radtriste** [comment]
Run this modification with feature update from https://github.com/kiegroup/kogito-cloud-operator/pull/282 => passed :)

**Review by radtriste — APPROVED** [review]
Run this modification with feature update from https://github.com/kiegroup/kogito-cloud-operator/pull/282 => passed :)

**Review by sutaakar — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
please cherry pick this commit: https://github.com/kiegroup/kogito-examples/pull/189/commits/65f44dc46fe49de0a66f569c248256d6db820ac6

Not sure if will it fail here, but on master was hiting a issue to build travel agency.

**Comment by radtriste** [comment]
we should cherry-pick that one as well: https://github.com/kiegroup/kogito-examples/pull/186

**Comment by evacchi** [comment]
@radtriste done and @spolti done

**Comment by radtriste** [comment]
thx !
will have a last test run before final approval

**Review by radtriste — APPROVED** [review]
tests ran ok

**Review by cristianonicolai — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@evacchi:
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch. 
Should I go ahead with squash or you want to take a look?

**Comment by evacchi** [comment]
@cristianonicolai last time I did it manually from CLI. for this branch we can also squash probably WDYT?

**Comment by cristianonicolai** [comment]
@evacchi sure, np, will squash the commits then. Can you take a look in the coflict now? :D

**Comment by radtriste** [comment]
gonna give a last test run with the latest merge

**Comment by radtriste** [comment]
tests ok

**Pull request merged**
