### PR TITLE
[KOGITO-5949] - Removing direct call to remote restcountries web service

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

In this PR, we replaced the direct calls to a remove web service with a Mock. Unfortunately, the remote service has an expired/invalid certificate so that we could see many error messages scattered along with our CI with this failed connection.

See https://issues.redhat.com/browse/KOGITO-5949

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]
Great job @ricardozanini

**Comment by ricardozanini** [comment]
We're green, merging it to unlock others.

**Comment by cristianonicolai** [comment]
@ricardozanini @radtriste we might need to backport this into 1.11.x wdyt?

**Comment by radtriste** [comment]
yes we do

**Comment by radtriste** [comment]
created https://github.com/kiegroup/kogito-examples/pull/900

**Pull request merged**
