### PR TITLE
KOGITO-4341 Infinispan upgrade to version 12

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1031
- https://github.com/kiegroup/kogito-runtimes/pull/1341
- https://github.com/kiegroup/kogito-apps/pull/815
- https://github.com/kiegroup/kogito-examples/pull/692

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by MarianMacik — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Pull request merged**
