### PR TITLE
[1.11.x] KOGITO-5790: Process user tasks with timer example using wrong jobs service image

### PR DESCRIPTION
**Pull request by pefernan**
backport of https://github.com/kiegroup/kogito-examples/pull/870

Also adding missing config on `process-usertasks-quarkus-with-console.`

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Review by mbiarnes — APPROVED** [review]

**Comment by Sara4994** [comment]
@pefernan Looks good to me. Thanks :)

**Review by Sara4994 — APPROVED** [review]

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Pull request merged**
