### PR TITLE
[1.11.x] Remove native profile from SW temperature example

### PR DESCRIPTION
**Pull request by ricardozanini**
It seems that in stable branch we already fixed this.

Error on CI:

```
[2021-12-08T16:50:41.278Z] [ERROR] Could not find goal 'native-image' in plugin io.quarkus:quarkus-maven-plugin:2.2.3.Final among available goals add-extension, add-extensions, analyze-call-tree, build, check-for-updates, create, create-extension, create-extension-legacy, create-jbang, dependency-tree, dev, generate-code, generate-code-tests, generate-config, help, list-categories, list-extensions, list-platforms, prepare, prepare-tests, remote-dev, remove-extension, remove-extensions, test -> [Help 1]
[2021-12-08T16:50:41.278Z] [ERROR] Could not find goal 'native-image' in plugin io.quarkus:quarkus-maven-plugin:2.2.3.Final among available goals add-extension, add-extensions, analyze-call-tree, build, check-for-updates, create, create-extension, create-extension-legacy, create-jbang, dependency-tree, dev, generate-code, generate-code-tests, generate-config, help, list-categories, list-extensions, list-platforms, prepare, prepare-tests, remote-dev, remove-extension, remove-extensions, test -> [Help 1]
[2021-12-08T16:50:41.278Z] [ERROR] 
[2021-12-08T16:50:41.278Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2021-12-08T16:50:41.278Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2021-12-08T16:50:41.278Z] [ERROR] 
[2021-12-08T16:50:41.278Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2021-12-08T16:50:41.278Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
```

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by ricardozanini** [comment]
@radtriste do you know why the GHA is complaining about this?

>   Error:   [kiegroup/kogito-runtimes] Trying to checking out kiegroup/kogito-runtimes into '/home/runner/work/kogito-examples/kogito-examples/kiegroup_kogito_runtimes'. It does not exist.

**Comment by radtriste** [comment]
looks like there is a problem with the pr config file for the buildchain ...

**Comment by manstis** [comment]
FWIW I had an issue with what appeared to be builds using stale source code:

https://github.com/kiegroup/kogito-apps/pull/1110#issuecomment-986684639

**Comment by manstis** [comment]
See https://github.com/kiegroup/kogito-apps/runs/4469074317?check_suite_focus=true too (also on `1.11.x`)

**Comment by manstis** [comment]
@jomarko FYI, this is the PR I mentioned that is also have GHA issues.

**Comment by ricardozanini** [comment]
@radtriste I think we are ready to merge?

**Review by radtriste — APPROVED** [review]

**Pull request merged**
