### PR TITLE
Update maven-surefire-plugin to pick up Quarkus tests

### PR DESCRIPTION
**Pull request by MarianMacik**
Guys,

after #1315, the [surefire declaration](https://github.com/kiegroup/kogito-examples/pull/1315/files#diff-f25fbb710ef5d87e99b3dc691fca60ff60ad266723eca33ae27b0a96af40abe1L152) was not added to child modules, so it was basically downgraded to an older version `2.12.x`, which is not compatible with `@QuarkusTest`. There are 2 options:
* Promote all `@QuarkusTest` to `@QuarkusIntegrationTest` which to me semantically doesn't make sense as these tests are not integrating anything. They are `HelloWorldTest`, `ParallelStateTest` and `HelloTest`.
* Add the surefire declaration to the modules which use `@QuarkusTest` effectively upgrading the version of the plugin - this is what I did. In case there are new unit tests added, I guess the surefire will be added by a programmer if needed.

In case you have another idea, just bring it up.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-examples] mandrel</b>

</details>

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#235` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/display/redirect

**Test results:**
- PASSED: 555
- FAILED: 16

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-default/kie_maven_plugin_test_kjar_10_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-default.kie-maven-plugin-test-kjar-10-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-yes-generate/kie_maven_plugin_test_kjar_10_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-yes-generate.kie-maven-plugin-test-kjar-10-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-default/kie_maven_plugin_test_kjar_11_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-default.kie-maven-plugin-test-kjar-11-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-yes-generate/kie_maven_plugin_test_kjar_11_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-yes-generate.kie-maven-plugin-test-kjar-11-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-12/kie_maven_plugin_test_kjar_12/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-12.kie-maven-plugin-test-kjar-12</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-13/kie_maven_plugin_test_kjar_13/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-13.kie-maven-plugin-test-kjar-13</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-13/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-14-ruleunits/kie_maven_plugin_test_kjar_14_ruleunits/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-14-ruleunits.kie-maven-plugin-test-kjar-14-ruleunits</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-14-ruleunits/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-2/kie_maven_plugin_test_kjar_2/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-2.kie-maven-plugin-test-kjar-2</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-2/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-3/kie_maven_plugin_test_kjar_3/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-3.kie-maven-plugin-test-kjar-3</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-3/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-exec-model/kie_maven_plugin_test_kjar_7_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-exec-model.kie-maven-plugin-test-kjar-7-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-no-exec-model/kie_maven_plugin_test_kjar_7_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-no-exec-model.kie-maven-plugin-test-kjar-7-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-exec-model/kie_maven_plugin_test_kjar_8_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-exec-model.kie-maven-plugin-test-kjar-8-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-no-exec-model/kie_maven_plugin_test_kjar_8_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-no-exec-model.kie-maven-plugin-test-kjar-8-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-exec-model/kie_maven_plugin_test_kjar_9_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-exec-model.kie-maven-plugin-test-kjar-9-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-no-exec-model/kie_maven_plugin_test_kjar_9_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-no-exec-model.kie-maven-plugin-test-kjar-9-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/235/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-setup/kie_maven_plugin_test_kjar_setup/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-setup.kie-maven-plugin-test-kjar-setup</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-setup/build.log for details.
</details>

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
jenkins rerun tests

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#236` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/display/redirect

**Test results:**
- PASSED: 555
- FAILED: 16

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-default/kie_maven_plugin_test_kjar_10_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-default.kie-maven-plugin-test-kjar-10-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-10-yes-generate/kie_maven_plugin_test_kjar_10_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-10-yes-generate.kie-maven-plugin-test-kjar-10-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-default/kie_maven_plugin_test_kjar_11_default/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-default.kie-maven-plugin-test-kjar-11-default</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-default/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-11-yes-generate/kie_maven_plugin_test_kjar_11_yes_generate/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-11-yes-generate.kie-maven-plugin-test-kjar-11-yes-generate</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-yes-generate/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-12/kie_maven_plugin_test_kjar_12/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-12.kie-maven-plugin-test-kjar-12</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-13/kie_maven_plugin_test_kjar_13/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-13.kie-maven-plugin-test-kjar-13</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-13/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-14-ruleunits/kie_maven_plugin_test_kjar_14_ruleunits/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-14-ruleunits.kie-maven-plugin-test-kjar-14-ruleunits</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-14-ruleunits/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-2/kie_maven_plugin_test_kjar_2/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-2.kie-maven-plugin-test-kjar-2</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-2/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-3/kie_maven_plugin_test_kjar_3/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-3.kie-maven-plugin-test-kjar-3</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-3/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-exec-model/kie_maven_plugin_test_kjar_7_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-exec-model.kie-maven-plugin-test-kjar-7-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-7-no-exec-model/kie_maven_plugin_test_kjar_7_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-7-no-exec-model.kie-maven-plugin-test-kjar-7-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-exec-model/kie_maven_plugin_test_kjar_8_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-exec-model.kie-maven-plugin-test-kjar-8-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-8-no-exec-model/kie_maven_plugin_test_kjar_8_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-8-no-exec-model.kie-maven-plugin-test-kjar-8-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-exec-model/kie_maven_plugin_test_kjar_9_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-exec-model.kie-maven-plugin-test-kjar-9-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-9-no-exec-model/kie_maven_plugin_test_kjar_9_no_exec_model/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-9-no-exec-model.kie-maven-plugin-test-kjar-9-no-exec-model</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-no-exec-model/build.log for details.
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/236/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-setup/kie_maven_plugin_test_kjar_setup/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-setup.kie-maven-plugin-test-kjar-setup</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-examples/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-setup/build.log for details.
</details>

**Review by jstastny-cz — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Comment by MarianMacik** [comment]
Test failures unrelated, they are present also in other PR runs.

**Pull request merged**
