### PR TITLE
KOGITO-6078 Fixes for outbox-mongo examples

### PR DESCRIPTION
**Pull request by tiagodolphine**
Related
https://github.com/kiegroup/kogito-runtimes/pull/1654

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Just added 2 comments in the code so it is more understandable. I think we are good to merge once the PR check is green.

**Review by cristianonicolai — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]
I think we are good to go.

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
@tiagodolphine 
```
io.fabric8.maven.docker.access.hc.http.HttpRequestException: {"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}
```
I think we are good to go anyway.

**Comment by tiagodolphine** [comment]
> I think we are good to go anyway.

I think so, I see this error on log since yesterday... that is not related.

@cristianonicolai @MarianMacik all good from my side.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
