### PR TITLE
[RHPAM-3649] Add missing dmn-event-driven modules to productized profile

### PR DESCRIPTION
**Pull request by antncl**
JIRA: https://issues.redhat.com/browse/RHPAM-3558
1.5.x (for CR2): https://github.com/kiegroup/kogito-examples/pull/685

Add the missing dmn-event-driven modules to the productized profile.

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
good with me but just a bit strange this was not accounted in the "spreadsheet circulation" when we discussed examples. @danielezonca any thoughts?

**Comment by antncl** [comment]
@tarilabs The original request was made here: https://issues.redhat.com/browse/BAPL-1817?focusedCommentId=16007337&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16007337 and the ticket to add them is here: https://issues.redhat.com/browse/RHPAM-3558

**Comment by mareknovotny** [comment]
@tkobayas please review to have it ready on monday for merging ;)

**Review by tkobayas — APPROVED** [review]
Thanks!

**Pull request merged**
