### PR TITLE
KOGITO-3862 - Make Docker images used by TestContainers compatible with Docker registry mirror

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/892
- https://github.com/kiegroup/kogito-examples/pull/457

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
+1

**Review by radtriste — APPROVED** [review]

**Review by evacchi — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
