### PR TITLE
[KOGITO-5682] Rename kogito events/messaging addons

### PR DESCRIPTION
**Pull request by fjtirado**
Depends on https://github.com/kiegroup/kogito-runtimes/pull/1519

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Review by ricardozanini — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Comment by fjtirado** [comment]
jenking run examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun examples tests

**Comment by ricardozanini** [comment]
Jenkins rerun examples tests

**Pull request merged**
