### PR TITLE
[KOGITO-6469] split quarkus and springboot based kogito examples

### PR DESCRIPTION
**Pull request by mariofusco**
JIRA: https://issues.redhat.com/browse/KOGITO-6469

Quarkus and Springobbot based examples require different configurations, to avoid problems like [this](https://issues.redhat.com/browse/DROOLS-6721). I also believe that people interested in Quarkus examples don't care much about Springboot ones and viceversa, so in general it makes sense to keep them separated.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
THANK YOU!

**Review by cristianonicolai — APPROVED** [review]

**Comment by mariofusco** [comment]
I'm not understanding why tests in `process-outbox-mongodb` for both quarkus and springboot are failing with following error

```
2022-01-03T18:42:02.4010291Z 18:41:59.575 [main] INFO  🐳 [docker/compose:1.29.2] - Container docker/compose:1.29.2 is starting: d6fd3a59e07374842e0bfa9b0d264054359046bfe1ff6457be64667bc7e55e14
2022-01-03T18:42:02.4136118Z 18:42:00.855 [main] ERROR 🐳 [docker/compose:1.29.2] - Could not start container
2022-01-03T18:42:02.4137427Z java.lang.IllegalStateException: Container did not start correctly.
```

@cristianonicolai @ricardozanini do you have any clue?

**Comment by mariofusco** [comment]
I cannot reproduce the problem locally and have no idea on what's going wrong in CI.
@ricardozanini @cristianonicolai @tiagodolphine can you please help with this?

**Comment by ricardozanini** [comment]
> I cannot reproduce the problem locally and have no idea on what's going wrong in CI. @ricardozanini @cristianonicolai @tiagodolphine can you please help with this?

No clue either, I'll take a look later.

**Comment by ricardozanini** [comment]
> > I cannot reproduce the problem locally and have no idea on what's going wrong in CI. @ricardozanini @cristianonicolai @tiagodolphine can you please help with this?
> 
> No clue either, I'll take a look later.

Hmm looks like the `.env` file is not being read. 🤔 

```
2022-01-04T10:13:06.5393292Z [main] ERROR 🐳 [docker/compose:1.29.2] - Log output from the failed container:
2022-01-04T10:13:06.5394155Z The DEBEZIUM_VERSION variable is not set. Defaulting to a blank string.
2022-01-04T10:13:06.5394997Z The KOGITO_DOCKERFILE variable is not set. Defaulting to a blank string.
```

Looking at the files changed, I can't find this file in the directory: https://github.com/kiegroup/kogito-examples/blob/main/process-outbox-mongodb-quarkus/.env

Can you double-check to see if it's there? You might miss it because it's a "hidden" file in *nix OS. You can't replicate in your env because you should have the images already in your registry. Try running `docker images | grep kogito/outbox`. Since they don't need to be built, the test succeeds. Try removing the images (`docker rmi <tagid>`) and you should be able to reproduce locally.

**Comment by mariofusco** [comment]
@ricardozanini thanks a lot for your finding. I had those `.env` files locally but they were not pushed on my commit because the `.gitignore` excluded them. [This](https://github.com/kiegroup/kogito-examples/pull/1053/commits/9fd714e2271fd33e98a98439afee57c1179f013f) should fix the problem.

**Comment by ricardozanini** [comment]
@mariofusco is there anything else left? Since CI is green now, I think we have a window to merge :D

**Review by tiagodolphine — APPROVED** [review]

**Pull request merged**
