### PR TITLE
KOGITO-5502 CORS issue of data-index in kogito-examples

### PR DESCRIPTION
**Pull request by bxf12315**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by nmirasch** [comment]
@bxf12315 We can not use 'nightly' images at examples regarding it breaks the idea of maintain the stable branch. Is that correct @radtriste @cristianonicolai?
Even It's true that to work at my local environment I need to use the 'nightly', I don't know what would be the good fix here.

**Comment by radtriste** [comment]
Indeed for now we can't as there is not automation to set back the released images on a release.
https://issues.redhat.com/browse/KOGITO-5475 is there to change that but had no time to look into it for now ...

**Comment by cristianonicolai** [comment]
@nmirasch correct, @bxf12315 we should not use nightly as it breaks the idea of `stable` branch.

**Review by cristianonicolai — CHANGES_REQUESTED** [review]
as mentioned, this should not be merged

**Comment by bxf12315** [comment]
> @nmirasch correct, @bxf12315 we should not use nightly as it breaks the idea of `stable` branch.

it's better way, but for now, kogito-examples are not work.

**Comment by radtriste** [comment]
What is not working ?
Those docker-compose should not be used in testing, they are just for user to test.
`master` is not the default branch so it should not harm the user.
Once that version is pushed to `stable`, the images should be released (note that 1.8 images are still not released due to infra problems, hopefully this will be solved for 1.9), so we don't need to use the nightly images on master

**Comment by bxf12315** [comment]
> What is not working ?
> Those docker-compose should not be used in testing, they are just for user to test.
> `master` is not the default branch so it should not harm the user.
> Once that version is pushed to `stable`, the images should be released (note that 1.8 images are still not released due to infra problems, hopefully this will be solved for 1.9), so we don't need to use the nightly images on master

all kogito apps will start, but we can not find any process instance in management-console and task-console, because of CORS issue of data-index. I think CORS issue fixed in nightly build.

**Comment by pefernan** [comment]
I think the issue that @bxf12315 is trying to solve is related to the current docker image for data index, were the I think that `{ ̣isNull: true }` query argument is not correctly working, this has been already fixed and the fix is present in the nightly images. I'd say that I won't add this change due to what's been already said.

**Comment by domhanak** [comment]
Closing as outdated

**Pull request closed without merging**
