### PR TITLE
[1.27.x] SecureRandom can't be static initialized at build time

### PR DESCRIPTION
**Pull request by spolti**
com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap.

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by spolti** [comment]
jenkins run native

**Comment by spolti** [comment]
jenkins run native

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Comment by cristianonicolai** [comment]
@spolti can you cherry pick this into main please.

**Pull request merged**
