### PR TITLE
RHPAM-4078 Add new Kogito and OptaPlanner8 quickstarts to 7.13

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/RHPAM-4078

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
lgtm

**Comment by mareknovotny** [comment]
please review @jstastny-cz @ibek

**Comment by ibek** [comment]
We can also add these new examples:
process-error-handling
process-mongodb-persistence
process-outbox-mongodb - I assume there will also be process-outbox-postgresql example in the near future https://issues.redhat.com/browse/BAPL-2197

@MarianMacik  Is process-performance example needed for perf-testing? We may want to add it as well.

Depending on BAPL-1976 we may need to add this quickstart in the future: https://github.com/kiegroup/kogito-examples/tree/stable/dmn-knative-quickstart-quarkus

**Comment by jstastny-cz** [comment]
@ibek do you want to add those also the the tracking Jiras? Cause comparing the Jira now, the lists in the PR and Jira match, so the requested items exceed the defined scope.

**Comment by ibek** [comment]
@jstastny-cz yes, I will add them to the jiras too

**Comment by ibek** [comment]
I updated the descriptions. Let's not include the mongodb ones after all - I made a separate requirement BAPL-2233 which we cannot add to 7.13 due to other priorities.

**Comment by Ginxo** [comment]
@ibek according to your comments and just to make the things more clear... is it your proposal just about additionally adding `process-error-handling`?
thanks!

**Comment by jstastny-cz** [comment]
@Ginxo @ibek I can confirm. At the moment we can add process-error-handling.

For others that we anticipate that might be added in future I marked them as out-of-scope for this effort, because they have their own trackers - I've made sure there's a note in each of those to add related modules into the productized profile here.

**Comment by Ginxo** [comment]
@ibek @jstastny-cz @mareknovotny `<module>process-error-handling</module>` added, please review again

**Comment by ibek** [comment]
Thanks for updating it. It looks good to me.

**Review by jstastny-cz — COMMENTED** [review]
Just one note, the addition of process-error-handling was inserted alphabetically into the existing modules list, while the rest of newly added modules are appended below (not inserted where it would belong alphabetically). I thought it was on purpose, now I am not sure.

**Comment by Ginxo** [comment]
good catch @jstastny-cz modules properly ordered (following the same order as the default profile is following).
This made me realize  `flexible-process-quarkus` was actually duplicated

**Review by mareknovotny — APPROVED** [review]

**Comment by Ginxo** [comment]
after internal chat with @jstastny-cz , all of the modules were alphabetically sorted out

**Review by jstastny-cz — APPROVED** [review]
Thank you, looks good.

**Pull request merged**
