### PR TITLE
[1.0.x] Update trusty demo operator images to 1.0 tag

### PR DESCRIPTION
**Pull request by r00ta**
This PR aims to update the trusty resources to the next tag release 1.0

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
@r00ta Can you please add a small description at least or make the title more explicit ?

**Review by radtriste — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Comment by r00ta** [comment]
Hi @radtriste , done

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@danielezonca happy with this change?

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
