### PR TITLE
KOGITO-9416 - Review supported modules

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/3077
- https://github.com/kiegroup/kogito-examples/pull/1699

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Review by fjtirado — COMMENTED** [review]
@cristianonicolai 
I think these are two PRs, isnt it?
One that remove event-quarkus from the productization set and another that format the POMS.

**Comment by cristianonicolai** [comment]
@fjtirado done, see https://github.com/kiegroup/kogito-examples/pull/1702

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Review by fjtirado — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Pull request merged**
