### PR TITLE
Remove optaplanner example from kogito-examples

### PR DESCRIPTION
**Pull request by ge0ffrey**
As discussed by PM. The dead, unused optaplanner example is being removed from kogito-examples. No impact on the other connections between OptaPlanner and Drools/Kogito, etc at this time.

@Ginxo After this PR is merged, would you mind adjusting the jenkins scripts accordingly to reduce jenkins PR workloads?

### CODE REVIEW

**Comment by ge0ffrey** [comment]
@mbiarnes This commit needs to be backported to the branch leading toward 7.13. Would you mind taking a look at that?

**Comment by Ginxo** [comment]
@ge0ffrey sure, but what exactly? can you please clarify? 
@radtriste FYI

**Comment by triceo** [comment]
@Ginxo @radtriste Since we are no longer part of kogito-examples, we need:
- OP CI to not execute downstream kogito-examples,
- for OP to not be a prerequisite of kogito-examples,
- and for the same to happen on PAM 7.13.

Feel free to ping me, I can help.

**Comment by ge0ffrey** [comment]
I am away to Devoxx UK this week, but if you guys could work with Lukas to get this through, backported and then CI adjusted, that would be great.

**Review by evacchi — APPROVED** [review]
if that's the requirement, then sure.

**Comment by radtriste** [comment]
> @Ginxo @radtriste Since we are no longer part of kogito-examples, we need:
> 
> * OP CI to not execute downstream kogito-examples,
> * for OP to not be a prerequisite of kogito-examples,
> * and for the same to happen on PAM 7.13.
> 
> Feel free to ping me, I can help.

@triceo you will need to update kogito-pipelines and optaplanner repo as well for downstream CI deps.

Please update those:
- https://github.com/kiegroup/kogito-pipelines/blob/main/.ci/project-dependencies.yaml#L73
- https://github.com/kiegroup/kogito-pipelines/blob/main/.ci/project-dependencies-quarkus.yaml#L89

Remove those:
- https://github.com/kiegroup/kogito-examples/blob/stable/.ci/jenkins/Jenkinsfile.native (all references to OptaPlanner)
- https://github.com/kiegroup/optaplanner/blob/main/.ci/jenkins/dsl/jobs.groovy#L40-L43

**Comment by triceo** [comment]
@radtriste Ok. WIll do in follow-up PRs.

**Pull request merged**
