### PR TITLE
[0.9.x] KOGITO-1822 - Create serverless greeting example for kogito and sprin…

### PR DESCRIPTION
**Pull request by tsurdilo**
…g boot

### CODE REVIEW

**Comment by tsurdilo** [comment]
DEPENDS ON https://github.com/kiegroup/kogito-runtimes/pull/438

**Review by ricardozanini — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]
Working as expected:

```sh
curl -X POST -H 'Content-Type:application/json' -H 'Accept:application/json' -d '{"workflowdata" : {"name": "John", "language": "English"}}' http://localhost:8080/jsongreet
{"id":"1eb7b71a-65fb-4ba7-9b8b-28a761780205","workflowdata":{"name":"John","language":"English","greeting":"Hello from JSON Workflow, "}}
```

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@tsurdilo this PR has conflict now.

**Review by evacchi — APPROVED** [review]

**Review by jstastny-cz — CHANGES_REQUESTED** [review]
Don't merge, we're past code-freeze on 0.9.x.

**Comment by tsurdilo** [comment]
rebased

**Comment by tsurdilo** [comment]
@jstastny-cz added swagger info to readme here as well.

**Comment by evacchi** [comment]
@jstastny-cz is this good to go?

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
