### PR TITLE
incubator-kie-issues#1483: Create a common Kie Flyway initializer for Kie Modules

### LINKED ISSUE #1483: Create a common Kie Flyway initializer addon
**Description of the problem**
Currently we are using the Platform (Quarkus/Spring-boot) Flyway integration to initialize the application Data Base at startup. When using different Kie modules that require persistence in our apps (ej: runtime, data-index, jobs, data-audit...), we configure Flyway to load and execute the SQL scripts from all those different modules in a single migration during the application startup.

This has some issues:
1. SQL scripts collisions: each module uses its own versioning in the `.sql` scripts (in the file name), and its possible to have version collisions during the Flyway execution if some of the modules have a similar version range in the scripts.
2. Version management: Flyway keeps the history of the applied migrations in a single table. Since each module defines its own version, it's possible that after a version upgrade, a module that requires running a new migration, cannot execute because a previous module already applied a "newer" version in a previous migration.
3. Complex application configuration: a part from the different versioning, each module may store the `.sql` script in different location causing the application require a complex setup in the `application.properties`, not pleasant for the customer. Ej ([link](https://github.com/kiegroup/kie-tools/blob/main/examples/jbpm-compact-architecture-example/src/main/resources/application.properties#L21)):
```
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=0.0
quarkus.flyway.locations=classpath:/db/migration,classpath:/db/jobs-service,classpath:/db/data-audit/postgresql
quarkus.flyway.table=FLYWAY_RUNTIME_SERVICE
```

**Proposed solution** 
The idea would be detach our scripts from the Platform Flyway integration and provide a mechanism that will make that each Kie Module that requires persistence, run an independent flyway instance that will keep track of the migrations history for each individual component. Leaving the platform specific Flyway integration (Quarkus/Spring-boot) for user specific purposes.

Each component can declare a simple properties file stored in a specific location (`META-INF/kie-flyway.properties`) with the  information required to run a Flyway instance on startup: This is:
* module name: name that identifies the module, if there are more than one module distribution (persistence-jdbc/persistence-postgresql) they should use the same name.
* Locations map: a map that will provide the script locations per database type, this way we can have modules loading different scripts depending on the DB. Optionally we could provide a `default` location to fallback in case we it doesn't provide the db specific location.
* 
Ej:
```
module=runtime-persistence # identifier of the module

# map of script locations per db type (if the module supports more than a single DB, ej: jdbc/jpa modules)
locations.postgresql=db/persistence/postgresql
locations.h2=db/persistence/h2
locations.default=... # Optional fallback locations
```

At startup the Kie Flyway Initialer will lookup for all the `META-INF/kie-flyway.properties` files and run a Flyway migration for each one using the application default datasource.

This mechanism can be enabled or disabled using the `kie.flyway.enabled=true/false` flag. By default in Quarkus will only be enabled for `test` and `dev` mode and will be disabled in Spring-Boot.

Examples will be updated accordingly to this new setup.

### PR DESCRIPTION
**Pull request by pefernan**
Closes https://github.com/apache/incubator-kie-issues/issues/1483

Ensemble: 
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3672
https://github.com/apache/incubator-kie-kogito-apps/pull/2102
https://github.com/apache/incubator-kie-kogito-examples/pull/2014

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2014 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/1/display/redirect

**Test results:**
- PASSED: 386
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/1/testReport/org.kie.kogito.examples/CallbackRestIT/PR_check___Build_projects___testCallbackRest/">PR check / Build projects / org.kie.kogito.examples.CallbackRestIT.testCallbackRest</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/1/testReport/org.kie.kogito.examples/TimeoutIT/PR_check___Build_projects___testSwitchStateWorkflow/">PR check / Build projects / org.kie.kogito.examples.TimeoutIT.testSwitchStateWorkflow</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/1/testReport/org.kie.kogito.examples/TimeoutIT/PR_check___Build_projects___testEventStateWorkflow/">PR check / Build projects / org.kie.kogito.examples.TimeoutIT.testEventStateWorkflow</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/1/testReport/org.kie.kogito.examples/TimeoutIT/PR_check___Build_projects___testWorkflow/">PR check / Build projects / org.kie.kogito.examples.TimeoutIT.testWorkflow</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/1/testReport/org.kie.kogito.examples/TimeoutIT/PR_check___Build_projects___testCallbackStateWorkflow/">PR check / Build projects / org.kie.kogito.examples.TimeoutIT.testCallbackStateWorkflow</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Comment by pefernan** [comment]
In this PR I tried addressing the examples that use flyway to consume the new initializer, however a lot of the examples are still using the old images. So I'll leave them as they are for now.

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2014 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/4/display/redirect

**Test results:**
- PASSED: 392
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2014/4/testReport/org.kie.kogito.examples.quarkus/GrafanaDockerComposeIT/testGrafanaDashboards/">org.kie.kogito.examples.quarkus.GrafanaDockerComposeIT.testGrafanaDashboards</a></summary>
1 expectation failed.<br/>JSON path title doesn't match.<br/>Expected: a collection containing "dmn-drools-quarkus-metrics_999-SNAPSHOT - hello - Operational Dashboard"<br/>  Actual: <[dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Operational Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - Hello - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Operational Dashboard]><br/>
</details>

**Review by martinweiler — APPROVED** [review]
LGTM @pefernan

**Review by martinweiler — APPROVED** [review]
LGTM @pefernan

**Review by elguardian — APPROVED** [review]
LGTM

**Review by porcelli — APPROVED** [review]

**Comment by porcelli** [comment]
not a bad idea to align everything with the new kie flyway. 

@pefernan  could you open an issue for future tracking?

**Comment by pefernan** [comment]
sure @porcelli, actually I think it would be good doing it.

**Comment by pefernan** [comment]
@porcelli there we go https://github.com/apache/incubator-kie/issues/6975

**Pull request merged**
