### PR TITLE
KOGITO-4450 - Set monitoring prometheus metrics endpoint content type

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4450

### Related PR:

kogito-runtimes: https://github.com/kiegroup/kogito-runtimes/pull/1079

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Jenkins retest this please

**Review by jiripetrlik — CHANGES_REQUESTED** [review]
@r00ta 
Can you please check also the value of content type in http response? It was the main request in KOGITO-4450.

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
> @r00ta
> Can you please check also the value of content type in http response? It was the main request in KOGITO-4450.

Hi Jiri, sure, done!

**Pull request merged**
