### PR TITLE
KOGITO-7376 - Move SW examples to serverless-workflow-examples

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on https://github.com/kiegroup/kogito-examples/pull/1277

### CODE REVIEW

**Review by spolti — APPROVED** [review]
Changes looks good, let's wait the tests finish to see if anything else will be needed.

**Comment by ricardozanini** [comment]
@hbelmiro can you change your example later to reflect this change? cc @jstastny-cz

**Review by ricardozanini — APPROVED** [review]
LGTM! I'd rather `serverless-workflow` than `serverless-workflow-examples`, but I think the former makes more sense to keep it aligned with quarkus and sb. Thank you!

**Comment by radtriste** [comment]
Please make sure testing in kogito-images and kogito-operator is updated with new examples paths

**Comment by cristianonicolai** [comment]
> Please make sure testing in kogito-images and kogito-operator is updated with new examples paths

@spolti can you look into that?

**Comment by jstastny-cz** [comment]
@cristianonicolai @ricardozanini is this just a step towards having the examples "standalone" projects containing full configuration? Cause here we're keeping parents and inheriting plugin management.

**Comment by cristianonicolai** [comment]
> @cristianonicolai @ricardozanini is this just a step towards having the examples "standalone" projects containing full configuration? Cause here we're keeping parents and inheriting plugin management.

@jstastny-cz correct, we still need to revisit poms to actually get it independently. But wanted to make sure that will also work with some of update version scripts we have.

**Review by krisv — CHANGES_REQUESTED** [review]
Might also need to update the references in the top readme?
https://github.com/kiegroup/kogito-examples/blob/stable/README.md?plain=1#L124

**Comment by spolti** [comment]
> 

I don't remember if we do use any serverless examples in there.
We can probably merge it and run the CI for images and operator later, @radtriste wdyt?

**Comment by ricardozanini** [comment]
@spolti we have a build test with a generated SW project only, IIRC

**Comment by spolti** [comment]
> @spolti we have a build test with a generated SW project only, IIRC

@ricardozanini correct, thanks for the tip
https://github.com/kiegroup/kogito-images/pull/1279

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Comment by cristianonicolai** [comment]
> 

@krisv fixed

**Review by krisv — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Pull request merged**
