### PR TITLE
KOGITO-1591: Remove magnet points from connectors

### PR DESCRIPTION
**Pull request by jomarko**
This PR updates persons.bpmn2 for process-quarkus-example and process-springboot-example
    
The complete list of processes that will be updated is maintained here https://issues.redhat.com/browse/KOGITO-1658

### CODE REVIEW

**Comment by domhanak** [comment]
@jomarko Build fails, @jstastny-cz looks like it is unable to download cypress for the MGMT console.

**Comment by domhanak** [comment]
How to restart the build here?
Jenkins retest this

**Review by romartin — APPROVED** [review]

**Comment by lazarotti** [comment]
@jomarko @domhanak this should be cherry-picked to 0.9.x branch in order to be in stable branch for dev preview

**Review by jstastny-cz — APPROVED** [review]

**Comment by jomarko** [comment]
@lazarotti thank you, cherry pick created here https://github.com/kiegroup/kogito-examples/pull/224

**Pull request merged**
