### PR TITLE
KOGITO-5443 - Replaced JDK image to fabric8/java-alpine-openjdk11-jre

### PR DESCRIPTION
**Pull request by dmartinol**
Many thanks for submitting your Pull Request :heart:! 
See: https://issues.redhat.com/browse/KOGITO-5443

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by dmartinol** [comment]
@ricardozanini could you please have a look at the changes?
Thanks,
Daniele

**Comment by ricardozanini** [comment]
@dmartinol, many thanks for this PR! Have you built and run some of them locally?

**Comment by ricardozanini** [comment]
Jenkins retest this

**Comment by dmartinol** [comment]
> @dmartinol, many thanks for this PR! Have you built and run some of them locally?

Hi @ricardozanini,
Of course, I did! Actually I built and launched all of them before and after the changes, to be sure it was effective
Glad to help,
Daniele

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@spolti, any considerations before merging?

**Comment by dmartinol** [comment]
Hi, I see it's not yet pulled into the upstream project, any further issues?

**Comment by ricardozanini** [comment]
> Hi, I see it's not yet pulled into the upstream project, any further issues?

I don't think we have any issues, but we need another approval before merging. @spolti can you please?

**Review by spolti — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Pull request merged**
