### PR TITLE
Initial implementation of OpenShift tests for Submarine examples

### PR DESCRIPTION
**Pull request by sutaakar**
@mswiderski Couple of questions:
- Should I add licence headers into the files?
- Right now tests are executed with basic build (mvn clean install). Considering that they need external resource (OpenShift) and takes quite a lot of time, would it have sense to move them to some profile?

### CODE REVIEW

**Comment by mswiderski** [comment]
> Should I add licence headers into the files?

yes

> Right now tests are executed with basic build (mvn clean install). Considering that they need external resource (OpenShift) and takes quite a lot of time, would it have sense to move them to some profile?

yes, let's have a dedicated profile for them

**Comment by sutaakar** [comment]
Licence headers added.
Integration tests skipped by default. They can be enabled by running Maven command with -DskipITs=false. Thinking that it may be better solution than using artificial profile just to enable tests.
@mswiderski What do you think about that?

**Comment by mswiderski** [comment]
@sutaakar yes, I'd add a profile for it that would make it more explicit

**Comment by sutaakar** [comment]
Added profile "openshift" enabling the tests.

**Review by mswiderski — APPROVED** [review]
@sutaakar is this ready to be merged?

**Comment by sutaakar** [comment]
Yes.

**Pull request merged**
