### PR TITLE
[kie-issues-249] Data Index Events changes for allowing historical data

### PR DESCRIPTION
**Pull request by elguardian**
issue https://github.com/apache/incubator-kie-issues/issues/249

depends on

https://github.com/apache/incubator-kie-drools/pull/5529
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241
https://github.com/apache/incubator-kie-kogito-apps/pull/1881

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/1/display/redirect

**Test results:**
- PASSED: 378
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/1/testReport/org.kie.kogito.examples/OpenVinoRestIT/testOpenvino/">org.kie.kogito.examples.OpenVinoRestIT.testOpenvino</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/3/display/redirect

**Test results:**
- PASSED: 368
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/3/testReport/org.acme.travels/ApprovalsProcessIT/PR_check___Build_projects___testApprovalProcess/">PR check / Build projects / org.acme.travels.ApprovalsProcessIT.testApprovalProcess</a></summary>
java.lang.reflect.InvocationTargetException
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/3/testReport/org.acme.travels/ApprovalsProcessIT/PR_check___Build_projects___testApprovalProcess/">PR check / Build projects / org.acme.travels.ApprovalsProcessIT.testApprovalProcess</a></summary>
java.lang.reflect.InvocationTargetException
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/3/testReport/org.acme.travels/ApprovalsRestIT/testStartApprovalUnauthenticated/">org.acme.travels.ApprovalsRestIT.testStartApprovalUnauthenticated</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/3/testReport/org.acme.travels/ApprovalsProcessTestIT/testApprovalProcessViaPhases/">org.acme.travels.ApprovalsProcessTestIT.testApprovalProcessViaPhases</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/3/testReport/org.kie.kogito.examples/OpenVinoRestIT/testOpenvino/">org.kie.kogito.examples.OpenVinoRestIT.testOpenvino</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/display/redirect

**Test results:**
- PASSED: 372
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [44930, 8083] should be listening)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.acme.travels.custom.lifecycle.quarkus/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.custom.lifecycle.quarkus.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.acme.travels.custom.lifecycle.quarkus/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.custom.lifecycle.quarkus.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [44976, 8083] should be listening)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.acme.travels.custom.lifecycle.springboot/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.custom.lifecycle.springboot.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.acme.travels.custom.lifecycle.springboot/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.custom.lifecycle.springboot.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/4/testReport/org.kie.kogito.examples/OpenVinoRestIT/testOpenvino/">org.kie.kogito.examples.OpenVinoRestIT.testOpenvino</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/display/redirect

**Test results:**
- PASSED: 372
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [36194, 8083] should be listening)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.acme.travels.custom.lifecycle.quarkus/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.custom.lifecycle.quarkus.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.acme.travels.custom.lifecycle.quarkus/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.custom.lifecycle.quarkus.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
Assertion condition defined as a lambda expression in org.kie.kogito.springboot.outbox.OutboxIT 1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <3><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events]><br/> within 1 minutes.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.acme.travels.custom.lifecycle.springboot/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.custom.lifecycle.springboot.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.acme.travels.custom.lifecycle.springboot/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.custom.lifecycle.springboot.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/5/testReport/org.acme.travels/ApprovalsProcessTestIT/testApprovalProcess/">org.acme.travels.ApprovalsProcessTestIT.testApprovalProcess</a></summary>
Failed to load ApplicationContext
</details>

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/display/redirect

**Test results:**
- PASSED: 373
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
Assertion condition defined as a lambda expression in org.kie.kogito.quarkus.outbox.OutboxIT 1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <3><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events]><br/> within 1 minutes.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/testReport/org.acme.travels.custom.lifecycle.quarkus/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.custom.lifecycle.quarkus.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/testReport/org.acme.travels.custom.lifecycle.quarkus/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.custom.lifecycle.quarkus.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
Assertion condition defined as a lambda expression in org.kie.kogito.springboot.outbox.OutboxIT 1 expectation failed.<br/>JSON path kogito-connector.topics doesn't match.<br/>Expected: a collection with size <3><br/>  Actual: <[kogito-processinstances-events, kogito-usertaskinstances-events]><br/> within 1 minutes.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/testReport/org.acme.travels.custom.lifecycle.springboot/ApprovalsProcessTest/testApprovalProcess/">org.acme.travels.custom.lifecycle.springboot.ApprovalsProcessTest.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/6/testReport/org.acme.travels.custom.lifecycle.springboot/ApprovalsProcessTest/testApprovalProcessViaPhases/">org.acme.travels.custom.lifecycle.springboot.ApprovalsProcessTest.testApprovalProcessViaPhases</a></summary>
expected: <1> but was: <5>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#7` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/7/display/redirect

**Test results:**
- PASSED: 377
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/7/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/7/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#8` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/8/display/redirect

**Test results:**
- PASSED: 377
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/8/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/8/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#9` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/9/display/redirect

**Test results:**
- PASSED: 377
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/9/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/9/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/1/display/redirect

**Test results:**
- PASSED: 47
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/1/testReport/org.acme/CustomRestDecisionTest/testRestDecision/">org.acme.CustomRestDecisionTest.testRestDecision</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>

**Comment by kie-ci3** [comment]
**PR job** `#10` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/10/display/redirect

**Test results:**
- PASSED: 377
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/10/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/10/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#11` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/11/display/redirect

**Test results:**
- PASSED: 377
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/11/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/11/testReport/org.kie.kogito.springboot.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.springboot.outbox.OutboxIT.testSendProcessEvents</a></summary>
expected: <true> but was: <false>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#12` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1815 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/12/display/redirect

**Test results:**
- PASSED: 378
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1815/12/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [36434, 8083] should be listening)
</details>

**Review by pefernan — APPROVED** [review]

**Review by martinweiler — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Pull request merged**
