### PR TITLE
KOGITO-6825 - Revert application.properties

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#531` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 432
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/531/testReport/org.acme.travel.tests.multimessaging.springboot/MultiMessagingIT/testProcess/">org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.multimessaging.springboot.MultiMessagingIT.testProcess(MultiMessagingIT.java:96)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/531/testReport/org.acme.travel.tests.messaging.springboot/MessagingIT/testProcess/">org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.springboot.MessagingIT.testProcess(MessagingIT.java:94)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/531/display/redirect

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by fjtirado** [comment]
@cristianonicolai I do not know how, but I tested the example manually and without these properties it was working nonetheless. I guess these properties are defined somewhere else. Anyway they do not harm, so lets go ahead

**Review by fjtirado — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#535` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 433
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/535/testReport/org.acme.travel.tests.messaging.quarkus/MessagingIT/testProcess/">org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <3><br/>	at org.acme.travel.tests.messaging.quarkus.MessagingIT.testProcess(MessagingIT.java:110)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/535/display/redirect

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Pull request merged**
