### PR TITLE
KOGITO-3596 Bump to Quarkus 1.9

### PR DESCRIPTION
**Pull request by evacchi**
see related 

- https://github.com/kiegroup/kogito-runtimes/pull/826
- https://github.com/kiegroup/kogito-apps/pull/491

----

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@evacchi missing Infinispan upgrade, see https://github.com/kiegroup/kogito-examples/pull/407/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R57

**Comment by evacchi** [comment]
I was leaving that to your PR @cristianonicolai

**Comment by cristianonicolai** [comment]
@evacchi sure, thats fine

**Review by tiagodolphine — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
