### PR TITLE
[KOGITO-4958] Add Spring Boot Actuator dependency

### PR DESCRIPTION
**Pull request by Kevin-Mok**
See: https://issues.redhat.com/browse/KOGITO-4958

## Description
This PR adds the Spring Boot Actuator dependency to the Spring Boot examples as the probes will now assume that the Actuator dependency is installed and use its endpoints.

## Related PR's
- [kogito-operator](https://github.com/kiegroup/kogito-operator/pull/841): [KOGITO-4898] Set probe defaults based on YAML action values

## Requirements
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]
@danielezonca, I think we need to start thinking of having a Kogito SpringBoot Starter. I'll finish my drafts once I get back from PTO, and we can talk more about it.

**Review by sutaakar — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
> @danielezonca, I think we need to start thinking of having a Kogito SpringBoot Starter. I'll finish my drafts once I get back from PTO, and we can talk more about it.

What do you mean? We have [this](https://github.com/kiegroup/kogito-runtimes/blob/master/kogito-springboot/kogito-springboot-starter/pom.xml#L28) but probably we need to review usage/design

**Comment by ricardozanini** [comment]
> > @danielezonca, I think we need to start thinking of having a Kogito SpringBoot Starter. I'll finish my drafts once I get back from PTO, and we can talk more about it.
> 
> What do you mean? We have [this](https://github.com/kiegroup/kogito-runtimes/blob/master/kogito-springboot/kogito-springboot-starter/pom.xml#L28) but probably we need to review usage/design

That's what I meant :)

**Comment by Kevin-Mok** [comment]
Is this ready to be merged?

**Pull request merged**
