### PR TITLE
[KOGITO-3610] Examples update to reflect the new Topics info endpoint

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Depends on: https://github.com/kiegroup/kogito-runtimes/pull/853

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by ricardozanini** [comment]
Jenkins test this please

**Review by evacchi — APPROVED** [review]

**Comment by evacchi** [comment]
@ricardozanini after this, if you have buffer, you should probably take a look at codegen in the knative addon (I have `@Deprecated` one of the knative-related generators)

**Comment by ricardozanini** [comment]
> @ricardozanini after this, if you have a buffer, you should probably take a look at codegen in the knative addon (I have `@Deprecated` one of the knative-related generators)

Unfortunately, I don't have it right now. I'm afraid we need to investigate a little bit more for outgoing HTTP connectors. The "deprecated" code decorates the message with CloudEvents metadata needed by the Smallrye implementation to invoke an HTTP endpoint. Let's keep this way now and come back after 1.0 to not jeopardize the Knative scenario.

**Review by cristianonicolai — APPROVED** [review]

**Comment by ricardozanini** [comment]
Jenkins test this please

**Comment by ricardozanini** [comment]
Jenkins test this please

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
