### PR TITLE
KOGITO-5455: CORS error on Springboot Examples With consoles

### PR DESCRIPTION
**Pull request by nmirasch**
jira related: https://issues.redhat.com/browse/KOGITO-5455

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by nmirasch** [comment]
Jenkins retest this

**Review by pefernan — APPROVED** [review]
+1 Thank you @nmirasch

**Review by radtriste — APPROVED** [review]

**Comment by pefernan** [comment]
jenkins retest this

**Comment by nmirasch** [comment]
Jenkins retest this

**Comment by nmirasch** [comment]
jenkins retest this please

**Pull request merged**
