### PR TITLE
FAI-293 - Update trusty demonstration README

### PR DESCRIPTION
**Pull request by r00ta**
Jira: https://issues.redhat.com/browse/FAI-293

Add clarification on the usage of the trusty demo

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by jiripetrlik — APPROVED** [review]
@r00ta 
Thank you for the quick fix of this README. LGTM

**Comment by r00ta** [comment]
Hi @jiripetrlik , thanks! Could you review/approve also the cherry pick for 1.0.0? https://github.com/kiegroup/kogito-examples/pull/465

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by danielezonca — APPROVED** [review]
LGTM :+1:

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Hi @jiripetrlik @danielezonca , I've reformulated the sentence according to the suggestion https://github.com/kiegroup/kogito-examples/pull/465#discussion_r527490228

**Comment by danielezonca** [comment]
jenkins retest this please

**Pull request merged**
