### PR TITLE
[RHPAM-3649] Add missing dmn-event-driven modules to productized profile [1.5.x]

### PR DESCRIPTION
**Pull request by antncl**
JIRA: https://issues.redhat.com/browse/RHPAM-3558
master: https://github.com/kiegroup/kogito-examples/pull/684

Add the missing dmn-event-driven modules to the productized profile.

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
good with me but just a bit strange this was not accounted in the "spreadsheet circulation" when we discussed examples. @danielezonca any thoughts?

**Review by tkobayas — APPROVED** [review]
Thanks @tarilabs !

> just a bit strange this was not accounted in the "spreadsheet circulation" when we discussed examples.

dmn-event-driven examples were additionally requested at a later point in time.

https://issues.redhat.com/browse/BAPL-1817?focusedCommentId=16007337&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16007337

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by Ginxo** [comment]
@tkobayas @tarilabs is `(default) Tests ` failure we should worry about? The job instance is not accessible

**Comment by tkobayas** [comment]
I cannot tell about `(default) Tests` as it's not accessible. If any doubt, re-run the test?

**Comment by antncl** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
@Ginxo @tarilabs @tkobayas @AntStephenson i guess the (default) Tests is from our old rhba jenkins while the new one is from Jcasc instance. @radtriste was announcing movement of jobs from the old one to new one, so maybe this is the glitch between migrated jobs.

**Comment by mareknovotny** [comment]
jenkins retest please

**Comment by antncl** [comment]
jenkins retest this

**Pull request merged**
