### PR TITLE
Add Onboarding Kogito Operator test

### PR DESCRIPTION
**Pull request by sutaakar**
@ricardozanini Can you please take a look?

### CODE REVIEW

**Comment by ricardozanini** [comment]
Is this test running on a real cluster? Cool.

Only thing that I could spot is that the onboarding service also has a label in the examples. And I didn’t see a check if the labels were applied in the services objects after KogitoApp creation. 

The objects creation seems fine :)

**Comment by sutaakar** [comment]
good catch, I will add it there.
Yes, it is tested on real cluster.

**Comment by sutaakar** [comment]
Minor enhancements here and there, service label test added.

**Review by ricardozanini — APPROVED** [review]

**Comment by sutaakar** [comment]
@mswiderski Can you please take a look/merge?

**Review by mswiderski — APPROVED** [review]

**Pull request merged**
