### PR TITLE
[DO-NOT-MERGE] [WIP] Quarkus 3 migration

### PR DESCRIPTION
**Pull request by tkobayas**
This is a WIP PR of migrating `kogito-examples` to Quarkus 3.5.2

- Update `before.sh` and java files for jbang.
- Run `before.sh` to generate `0001_before_sh.patch`
- Fix manual patch
- Apply patches
- ~~Update `2.0.0-SNAPSHOT` to `3.0.0-SNAPSHOT`~~

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
@mariofusco Feel free to replace this PR with your own PR for cross repo CI.

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1832 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1832/1/display/redirect

**Test results:**
- PASSED: 17
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1832/1/testReport/org.acme.loanbroker/AppResourceTest/testCloudEventNotifyNewQuote/">org.acme.loanbroker.AppResourceTest.testCloudEventNotifyNewQuote</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <400>.<br/>
</details>

**Comment by tkobayas** [comment]
**Issue A)**

Many projects (e.g. `serverless-workflow-annotations-description`) under `serverless-workflow-examples` and `trusty-tracing-quarkus-devservices` under `kogito-quarkus-examples` have the build issue. 
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.5.2:build (default) on project serverless-workflow-annotations-description: Execution default of goal io.quarkus:quarkus-maven-plugin:3.5.2:build failed: A required class was missing while executing io.quarkus:quarkus-maven-plugin:3.5.2:build: io/quarkus/devconsole/spi/DevConsoleTemplateInfoBuildItem
```

**Comment by tkobayas** [comment]
**Issue B)**

Test failure in `flexible-process-quarkus`.

```
2023-11-28 21:54:04,230 INFO  [org.kie.kog.qua.pro.dev.DevModeWorkflowLogger] (executor-thread-1) Triggered node 'Questionnaire' for process 'serviceDesk' (9555d487-6a0d-4278-9105-a3e437078ada)
Request method:	GET
Request URI:	http://localhost:41793/serviceDesk/9555d487-6a0d-4278-9105-a3e437078ada/tasks
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=*/*
				Content-Type=application/json
Cookies:		<none>
Multiparts:		<none>
Body:			<none>

HTTP/1.1 200 OK
Content-Type: application/json
content-length: 180

[
    {
        "id": "69c968e4-9aff-4b4c-9eb8-2f23f5026e04",
        "name": "Questionnaire",
        "state": 0,
        "phase": "active",
        "phaseStatus": "Ready",
        "parameters": {
            
        },
        "results": {
            "evaluation": null,
            "comment": null
        }
    }
]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.54 s <<< FAILURE! -- in org.kie.kogito.flexible.example.quarkus.ServiceDeskProcessTest
[ERROR] org.kie.kogito.flexible.example.quarkus.ServiceDeskProcessTest.testSupportCaseExample -- Time elapsed: 2.758 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
JSON path $.size doesn't match.
Expected: is <1>
  Actual: <[]>

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:270)
	at io.restassured.specification.ResponseSpecification$body$2.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:117)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
	at org.kie.kogito.flexible.example.quarkus.ServiceDeskProcessTest.sendQuestionnaire(ServiceDeskProcessTest.java:171)
	at org.kie.kogito.flexible.example.quarkus.ServiceDeskProcessTest.testSupportCaseExample(ServiceDeskProcessTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1014)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:828)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

2023-11-28 21:54:04,669 INFO  [io.quarkus] (main) flexible-process-quarkus stopped in 0.309s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ServiceDeskProcessTest.testSupportCaseExample:56->sendQuestionnaire:171 1 expectation failed.
JSON path $.size doesn't match.
Expected: is <1>
  Actual: <[]>
```

**Comment by tkobayas** [comment]
A similar issue in `process-infinispan-persistence-quarkus`
```
[ERROR] Failures: 
[ERROR]   DealsRestIT.testDealsRest:80 1 expectation failed.
JSON path $.size doesn't match.
Expected: is <1>
  Actual: <[]>
```

**Pull request closed without merging**
