### PR TITLE
Revert "KOGITO-4505 Use legacy-jar packaging in all Quarkus examples"

### PR DESCRIPTION
**Pull request by spolti**
Reverts kiegroup/kogito-examples#582
Issue fixed on images as part of https://issues.redhat.com/browse/KOGITO-4503

### CODE REVIEW

**Comment by spolti** [comment]
probably it failed because I reverted the the changes using the previous PR's revert button.
@radtriste is there a way to make the tests starts without redo the changes on my fork?

**Comment by spolti** [comment]
depends on https://github.com/kiegroup/kogito-images/pull/378

**Comment by cristianonicolai** [comment]
@spolti I think we might need to hold this as master will be reverted to 1.11, right @evacchi?

**Comment by evacchi** [comment]
I think it may be worth to do the opposite change and use fast-jar explicitly (forward compatibility), WDYT @cristianonicolai ?

**Comment by cristianonicolai** [comment]
> I think it may be worth to do the opposite change and use fast-jar explicitly (forward compatibility), WDYT @cristianonicolai ?

makes sense, +1

**Comment by radtriste** [comment]
@spolti @evacchi I guess this one can be close as we are moving forward with https://github.com/kiegroup/kogito-examples/pull/601

**Pull request closed without merging**
