### PR TITLE
KOGITO-6155 fix quarkus openapi endpoint URL

### PR DESCRIPTION
**Pull request by jstastny-cz**
https://issues.redhat.com/browse/KOGITO-6155

Fixing quarkus examples readme files to use openapi endpoint URL served by quarkus by default.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by MarianMacik — APPROVED** [review]
:+1:

**Comment by jstastny-cz** [comment]
jenkins retest this

**Review by evacchi — APPROVED** [review]

**Comment by jstastny-cz** [comment]
Jenkins retest this

**Comment by jstastny-cz** [comment]
rebased

**Comment by MarianMacik** [comment]
@jstastny-cz do we still want to merge this?

**Comment by jstastny-cz** [comment]
Closing, it's way too outdated to be reused.

**Pull request closed without merging**
