### PR TITLE
Update Notification Bot to not clip the issue link

### PR DESCRIPTION
**Pull request by ricardozanini**
A Small change in the bot to not clip the issue link when the issue description is too large.

@danielezonca @tarilabs as soon as you approve, I'll replicate the changes to the other repos.

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
So links come first and description comes later (up to truncated)?
LGTM thanks

**Comment by ricardozanini** [comment]
I guess we can ignore this CI error? 🤔 

```
  Error:   [kiegroup/kogito-runtimes] Trying to checking out kiegroup/kogito-runtimes into '/home/runner/work/kogito-examples/kogito-examples/kiegroup_kogito_runtimes'. It does not exist.
```

**Comment by danielezonca** [comment]
@ricardozanini 
Thanks for the PR :)

Please update target branch to `main` instead of `stable`

What about add issue id in the `topic` as
```yaml
        topic: 'GitHub Issues ${{ github.event.issue.id }} - ${{ github.event.issue.title }}'
```
?

I'm thinking also at `${{ github.event.repo.name }}` so that it is clear if it is `kiegroup/kogito-runtimes` or `kiegroup/kogito-examples` or `kiegroup/kogito-apps` but I don't know if this makes the title too long 🤔 
```yaml
        topic: 'GitHub ${{ github.event.repo.name }} Issue ${{ github.event.issue.id }} - ${{ github.event.issue.title }}'
```

Wdyt?

**Comment by ricardozanini** [comment]
> Please update target branch to main instead of stable

LOL I did it in the UI, I'll close this one and open a new one.

**Pull request closed without merging**
