### PR TITLE
KOGITO-3494 Update OptaPlanner version to 8.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by rsynek**
https://issues.redhat.com/browse/KOGITO-3494

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins test this

**Review by radtriste — APPROVED** [review]
let's see the result from pipeline check

**Comment by radtriste** [comment]
@danielezonca @cristianonicolai can one of you merge that one ?

**Review by ge0ffrey — APPROVED** [review]

**Pull request merged**
